// Auto-generated via Google Places API — 2026-02-12T12:23:39.450Z
// 34 restaurants in BOSTON

export const BOSTON_RESTAURANTS = [
  { name: 'The Salty Pig', slug: 'thesaltypig', category: 'restaurant', metros: ['boston'] },
  { name: 'Saltie Girl', slug: 'saltiegirl', category: 'restaurant', metros: ['boston'] },
  { name: 'Beehive Restaurant', slug: 'beehiverestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Mamma Maria', slug: 'mammamaria', category: 'restaurant', metros: ['boston'] },
  { name: 'Grill 23 & Bar', slug: 'grill23bar', category: 'restaurant', metros: ['boston'] },
  { name: 'Coquette', slug: 'coquette', category: 'restaurant', metros: ['boston'] },
  { name: 'Atlantic Fish Company', slug: 'atlanticfishcompany', category: 'seafood', metros: ['boston'] },
  { name: 'Boston Sail Loft', slug: 'bostonsailloft', category: 'restaurant', metros: ['boston'] },
  { name: 'Legal Sea Foods - Harborside', slug: 'legalseafoods-harborside', category: 'restaurant', metros: ['boston'] },
  { name: 'Ostra', slug: 'ostra', category: 'restaurant', metros: ['boston'] },
  { name: 'James Hook & Co', slug: 'jameshookco', category: 'restaurant', metros: ['boston'] },
  { name: 'The Oceanaire Seafood Room', slug: 'theoceanaireseafoodroom', category: 'seafood', metros: ['boston'] },
  { name: 'Chart House', slug: 'charthouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Union Oyster House', slug: 'unionoysterhouse', category: 'seafood', metros: ['boston'] },
  { name: 'STK Steakhouse', slug: 'stksteakhouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Wusong Tiki Bar', slug: 'wusongtikibar', category: 'restaurant', metros: ['boston'] },
  { name: 'Highland Kitchen', slug: 'highlandkitchen', category: 'restaurant', metros: ['boston'] },
  { name: 'Carmelina\'s', slug: 'carmelinas', category: 'restaurant', metros: ['boston'] },
  { name: 'La Famiglia Giorgio\'s Restaurant', slug: 'lafamigliagiorgiosrestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Giacomo\'s Boston North End', slug: 'giacomosbostonnorthend', category: 'restaurant', metros: ['boston'] },
  { name: 'Prezza', slug: 'prezza', category: 'restaurant', metros: ['boston'] },
  { name: 'Limoncello', slug: 'limoncello', category: 'restaurant', metros: ['boston'] },
  { name: 'Little Sage', slug: 'littlesage', category: 'restaurant', metros: ['boston'] },
  { name: 'Antico Forno', slug: 'anticoforno', category: 'restaurant', metros: ['boston'] },
  { name: 'Bricco', slug: 'bricco', category: 'restaurant', metros: ['boston'] },
  { name: 'Cantina Italiana', slug: 'cantinaitaliana', category: 'italian', metros: ['boston'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['boston'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['boston'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['boston'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['boston'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['boston'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['boston'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['boston'] },
];
