// Auto-generated via Google Places API — 2026-02-12T12:23:20.847Z
// 67 restaurants in CHICAGO

export const CHICAGO_RESTAURANTS = [
  { name: 'Girl & The Goat', slug: 'girlthegoat', category: 'restaurant', metros: ['chicago'] },
  { name: 'River Roast', slug: 'riverroast', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Dearborn', slug: 'thedearborn', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Purple Pig Restaurant', slug: 'thepurplepigrestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'Elephant & Castle', slug: 'elephantcastle', category: 'restaurant', metros: ['chicago'] },
  { name: 'Alla Vita', slug: 'allavita', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carnivale Chicago', slug: 'carnivalechicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Beatnik On The River', slug: 'beatnikontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Quartino Ristorante', slug: 'quartinoristorante', category: 'restaurant', metros: ['chicago'] },
  { name: 'Eataly', slug: 'eataly', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pizzeria Portofino', slug: 'pizzeriaportofino', category: 'restaurant', metros: ['chicago'] },
  { name: 'Giordano\'s', slug: 'giordanos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Gino\'s East', slug: 'ginoseast', category: 'restaurant', metros: ['chicago'] },
  { name: 'Zarella Pizzeria & Taverna', slug: 'zarellapizzeriataverna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pequod\'s Pizza', slug: 'pequodspizza', category: 'pizza', metros: ['chicago'] },
  { name: 'Spacca Napoli Pizzeria', slug: 'spaccanapolipizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Lou Malnati\'s Pizzeria', slug: 'loumalnatispizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Robert\'s Pizza and Dough Company', slug: 'robertspizzaanddoughcompany', category: 'pizza', metros: ['chicago'] },
  { name: 'Labriola Ristorante - Chicago', slug: 'labriolaristorante-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Perch Kitchen and Tap', slug: 'theperchkitchenandtap', category: 'restaurant', metros: ['chicago'] },
  { name: 'Big Star Wicker Park', slug: 'bigstarwickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Paradise Park | Pizza & Patio', slug: 'paradiseparkpizzapatio', category: 'pizza', metros: ['chicago'] },
  { name: 'Elia Chicago', slug: 'eliachicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ina Mae', slug: 'inamae', category: 'restaurant', metros: ['chicago'] },
  { name: 'Amaru', slug: 'amaru', category: 'restaurant', metros: ['chicago'] },
  { name: 'Handlebar', slug: 'handlebar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Piece Pizzeria and Brewery', slug: 'piecepizzeriaandbrewery', category: 'restaurant', metros: ['chicago'] },
  { name: 'Cafe Robey', slug: 'caferobey', category: 'cafe', metros: ['chicago'] },
  { name: 'Bangers & Lace Wicker Park', slug: 'bangerslacewickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Summer House Santa Monica', slug: 'summerhousesantamonica', category: 'restaurant', metros: ['chicago'] },
  { name: 'Boka', slug: 'boka', category: 'restaurant', metros: ['chicago'] },
  { name: 'Blue Door Farm Stand', slug: 'bluedoorfarmstand', category: 'restaurant', metros: ['chicago'] },
  { name: 'North Pond', slug: 'northpond', category: 'restaurant', metros: ['chicago'] },
  { name: 'Mon Ami Gabi', slug: 'monamigabi', category: 'restaurant', metros: ['chicago'] },
  { name: 'GEMINI', slug: 'gemini', category: 'restaurant', metros: ['chicago'] },
  { name: 'Armitage Alehouse', slug: 'armitagealehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'DeNucci\'s Lincoln Park', slug: 'denuccislincolnpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Willow Room', slug: 'willowroom', category: 'restaurant', metros: ['chicago'] },
  { name: 'Aba', slug: 'aba', category: 'restaurant', metros: ['chicago'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['chicago'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['chicago'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['chicago'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Café No Sé', slug: 'cafnos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Costera Cocina Tulum - Chicago', slug: 'costeracocinatulum-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ayayay - Mexican Eatery', slug: 'ayayay-mexicaneatery', category: 'mexican', metros: ['chicago'] },
  { name: 'Mercadito', slug: 'mercadito', category: 'restaurant', metros: ['chicago'] },
  { name: 'Casa Tulum', slug: 'casatulum', category: 'restaurant', metros: ['chicago'] },
  { name: 'Tzuco', slug: 'tzuco', category: 'restaurant', metros: ['chicago'] },
  { name: 'Momento Cantina', slug: 'momentocantina', category: 'restaurant', metros: ['chicago'] },
  { name: 'Matilda Restaurant', slug: 'matildarestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'XOCO', slug: 'xoco', category: 'restaurant', metros: ['chicago'] },
  { name: 'La Luna', slug: 'laluna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Frontera Grill', slug: 'fronteragrill', category: 'restaurant', metros: ['chicago'] },
  { name: 'Green Street Smoked Meats', slug: 'greenstreetsmokedmeats', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoque BBQ', slug: 'smoquebbq', category: 'korean', metros: ['chicago'] },
  { name: 'Bub City', slug: 'bubcity', category: 'restaurant', metros: ['chicago'] },
  { name: 'Chubby Cattle BBQ | Chicago', slug: 'chubbycattlebbqchicago', category: 'korean', metros: ['chicago'] },
  { name: 'Offset BBQ', slug: 'offsetbbq', category: 'korean', metros: ['chicago'] },
  { name: 'Honky Tonk BBQ / The Tonk', slug: 'honkytonkbbqthetonk', category: 'korean', metros: ['chicago'] },
  { name: 'Chicago Q', slug: 'chicagoq', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carson’s Prime Steaks & Famous Barbecue – Chicago (Streeterville)', slug: 'carsonsprimesteaksfamousbarbecuechicagos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Soul & Smoke - Avondale at Rockwell on the River', slug: 'soulsmoke-avondaleatrockwellontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoke Daddy BBQ - Wrigleyville', slug: 'smokedaddybbq-wrigleyville', category: 'korean', metros: ['chicago'] },
];
