// Auto-generated via Google Places API — 2026-02-12T12:23:28.860Z
// 43 restaurants in LA

export const LA_RESTAURANTS = [
  { name: 'Perch', slug: 'perch', category: 'restaurant', metros: ['la'] },
  { name: 'JOEY DTLA', slug: 'joeydtla', category: 'restaurant', metros: ['la'] },
  { name: 'Little Beast Restaurant', slug: 'littlebeastrestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Yamashiro Hollywood', slug: 'yamashirohollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Musso & Frank Grill', slug: 'mussofrankgrill', category: 'restaurant', metros: ['la'] },
  { name: 'Providence', slug: 'providence', category: 'restaurant', metros: ['la'] },
  { name: 'La Boheme', slug: 'laboheme', category: 'restaurant', metros: ['la'] },
  { name: 'Superba Food + Bread Hollywood', slug: 'superbafoodbreadhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'The Little Door', slug: 'thelittledoor', category: 'restaurant', metros: ['la'] },
  { name: 'Girl & the Goat Los Angeles', slug: 'girlthegoatlosangeles', category: 'restaurant', metros: ['la'] },
  { name: 'Jemma Hollywood', slug: 'jemmahollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Running Goose', slug: 'runninggoose', category: 'restaurant', metros: ['la'] },
  { name: 'Mother Wolf', slug: 'motherwolf', category: 'restaurant', metros: ['la'] },
  { name: 'UOVO Santa Monica', slug: 'uovosantamonica', category: 'restaurant', metros: ['la'] },
  { name: 'Guelaguetza Restaurant', slug: 'guelaguetzarestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Holbox', slug: 'holbox', category: 'restaurant', metros: ['la'] },
  { name: 'El Cholo - The Original', slug: 'elcholo-theoriginal', category: 'restaurant', metros: ['la'] },
  { name: 'Guisados', slug: 'guisados', category: 'restaurant', metros: ['la'] },
  { name: 'Sol Agave LA LIVE', slug: 'solagavelalive', category: 'restaurant', metros: ['la'] },
  { name: 'Gracias Madre', slug: 'graciasmadre', category: 'restaurant', metros: ['la'] },
  { name: 'El Compadre Restaurant of Hollywood', slug: 'elcompadrerestaurantofhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Casita Del Campo', slug: 'casitadelcampo', category: 'restaurant', metros: ['la'] },
  { name: 'Javier\'s', slug: 'javiers', category: 'restaurant', metros: ['la'] },
  { name: 'Madre Restaurant', slug: 'madrerestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Hae Jang Chon Korean BBQ Restaurant', slug: 'haejangchonkoreanbbqrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Sun Nong Dan', slug: 'sunnongdan', category: 'restaurant', metros: ['la'] },
  { name: 'Jumsim', slug: 'jumsim', category: 'restaurant', metros: ['la'] },
  { name: 'Hanu K BBQ', slug: 'hanukbbq', category: 'korean', metros: ['la'] },
  { name: 'Park\'s BBQ', slug: 'parksbbq', category: 'korean', metros: ['la'] },
  { name: 'Jun Won Dak IG @junwon_la', slug: 'junwondakigjunwonla', category: 'restaurant', metros: ['la'] },
  { name: 'Kobawoo House', slug: 'kobawoohouse', category: 'restaurant', metros: ['la'] },
  { name: 'HOJOKBAN LA', slug: 'hojokbanla', category: 'restaurant', metros: ['la'] },
  { name: '여기요 YeoGiYo 한식전문 | Premium Korean Restaurant', slug: 'yeogiyopremiumkoreanrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Baroo', slug: 'baroo', category: 'restaurant', metros: ['la'] },
  { name: 'Bacari Silverlake', slug: 'bacarisilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Sonmari', slug: 'sonmari', category: 'restaurant', metros: ['la'] },
  { name: 'Pine and Crane Silverlake', slug: 'pineandcranesilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Botanica Restaurant and Market', slug: 'botanicarestaurantandmarket', category: 'restaurant', metros: ['la'] },
  { name: 'Izakaya Osen', slug: 'izakayaosen', category: 'restaurant', metros: ['la'] },
  { name: 'Tacolina', slug: 'tacolina', category: 'mexican', metros: ['la'] },
  { name: 'Ceviche Project', slug: 'cevicheproject', category: 'restaurant', metros: ['la'] },
  { name: 'The Black Cat', slug: 'theblackcat', category: 'restaurant', metros: ['la'] },
  { name: 'Santo Silverlake', slug: 'santosilverlake', category: 'restaurant', metros: ['la'] },
];
