// Auto-generated via Google Places API — 2026-02-12T12:23:47.746Z
// 35 restaurants in MIAMI

export const MIAMI_RESTAURANTS = [
  { name: 'Komodo Miami', slug: 'komodomiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Moxies Miami Restaurant', slug: 'moxiesmiamirestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Tua Cucina Brickell', slug: 'casatuacucinabrickell', category: 'restaurant', metros: ['miami'] },
  { name: 'Nikki Beach Miami Beach', slug: 'nikkibeachmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Old\'s Havana Cuban Bar & Cocina', slug: 'oldshavanacubanbarcocina', category: 'restaurant', metros: ['miami'] },
  { name: 'Versailles Restaurant Cuban Cuisine', slug: 'versaillesrestaurantcubancuisine', category: 'restaurant', metros: ['miami'] },
  { name: 'La Mulata | Cuban Restaurant Miami Beach', slug: 'lamulatacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Esquina Cubana | Cuban Restaurant Miami Beach', slug: 'esquinacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Havana Vieja | Latin Restaurant Miami Beach', slug: 'havanaviejalatinrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Sala\'o Cuban Restaurant & Bar - Live music', slug: 'salaocubanrestaurantbar-livemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Marabu Restaurant', slug: 'maraburestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Alma Cubana | Cuban Restaurant Miami Beach', slug: 'almacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Cubana | Restaurant & Live Music', slug: 'casacubanarestaurantlivemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Little Havana', slug: 'littlehavana', category: 'restaurant', metros: ['miami'] },
  { name: 'Mayami Wynwood', slug: 'mayamiwynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'Sha Wynwood', slug: 'shawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'R House Wynwood', slug: 'rhousewynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'BAKAN', slug: 'bakan', category: 'restaurant', metros: ['miami'] },
  { name: 'Astra Miami Rooftop', slug: 'astramiamirooftop', category: 'restaurant', metros: ['miami'] },
  { name: 'Le Chick Miami', slug: 'lechickmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Ossobuco Miami - Steak house', slug: 'ossobucomiami-steakhouse', category: 'restaurant', metros: ['miami'] },
  { name: 'KYU Miami', slug: 'kyumiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Manta Wynwood', slug: 'mantawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'MIAM CAFE-WYNWOOD', slug: 'miamcafe-wynwood', category: 'cafe', metros: ['miami'] },
  { name: 'Joe\'s Stone Crab', slug: 'joesstonecrab', category: 'restaurant', metros: ['miami'] },
  { name: 'Mercato della Pescheria Miami Beach', slug: 'mercatodellapescheriamiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Españolita Miami Beach 🌹💃SEAFOOD&STEAKHOUSE', slug: 'espaolitamiamibeachseafoodsteakhouse', category: 'seafood', metros: ['miami'] },
  { name: 'Nettuno Italian Seafood & Oysters', slug: 'nettunoitalianseafoodoysters', category: 'seafood', metros: ['miami'] },
  { name: 'A Fish Called Avalon', slug: 'afishcalledavalon', category: 'seafood', metros: ['miami'] },
  { name: 'CORALLO 🇮🇹 Amalfi coast', slug: 'coralloamalficoast', category: 'restaurant', metros: ['miami'] },
  { name: 'Rusty Pelican Miami', slug: 'rustypelicanmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'CVI.CHE 105 South Beach', slug: 'cviche105southbeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Osteria Positano', slug: 'osteriapositano', category: 'restaurant', metros: ['miami'] },
  { name: 'CJ\'s Crab Shack', slug: 'cjscrabshack', category: 'restaurant', metros: ['miami'] },
  { name: 'Felice Brickell', slug: 'felicebrickell', category: 'restaurant', metros: ['miami'] },
];
