
// ─── New City Restaurants (Google Places discovery, Feb 12) ────

export const ATLANTA_RESTAURANTS: RestaurantData[] = [
  { name: 'TWO urban licks', slug: 'twourbanlicks', category: 'restaurant', metros: ['atlanta'] },
  { name: '9 Mile Station', slug: '9milestation', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Mary Mac\'s Tea Room', slug: 'marymacstearoom', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Sugar Factory American Brasserie - Atlanta', slug: 'sugarfactoryamericanbrasserie-atlanta', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Hungry AF Downtown', slug: 'hungryafdowntown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Marcel', slug: 'marcel', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ray\'s In the City', slug: 'raysinthecity', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ladybird Grove & Mess Hall', slug: 'ladybirdgrovemesshall', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Sun Dial Restaurant, Bar & View', slug: 'thesundialrestaurantbarview', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Canoe', slug: 'canoe', category: 'restaurant', metros: ['atlanta'] },
  { name: 'South City Kitchen Midtown', slug: 'southcitykitchenmidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'El Viñedo Local', slug: 'elviedolocal', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Consulate Restaurant', slug: 'theconsulaterestaurant', category: 'restaurant', metros: ['atlanta'] },
  { name: '5Church Midtown', slug: '5churchmidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Crescent City Kitchen', slug: 'crescentcitykitchen', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Boqueria Colony Sqaure', slug: 'boqueriacolonysqaure', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Wagyu House Atlanta', slug: 'wagyuhouseatlanta', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ecco Midtown', slug: 'eccomidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Yebo Beach Haus', slug: 'yebobeachhaus', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Delbar - Inman Park', slug: 'delbar-inmanpark', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Yeppa & Co. - Beltline', slug: 'yeppaco-beltline', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Barcelona Wine Bar', slug: 'barcelonawinebar', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Eclipse di Luna - Beltline', slug: 'eclipsediluna-beltline', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Kitty Dare', slug: 'kittydare', category: 'restaurant', metros: ['atlanta'] },
  { name: 'BeetleCat', slug: 'beetlecat', category: 'restaurant', metros: ['atlanta'] },
  { name: 'a mano', slug: 'amano', category: 'restaurant', metros: ['atlanta'] },
  { name: 'BoccaLupo', slug: 'boccalupo', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Sotto Sotto Restaurant', slug: 'sottosottorestaurant', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Iberian Pig', slug: 'theiberianpig', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Kimball House', slug: 'kimballhouse', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Cap\'t Loui - Decatur', slug: 'captloui-decatur', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Louisiana Bistreaux Seafood Kitchen Decatur', slug: 'louisianabistreauxseafoodkitchendecatur', category: 'seafood', metros: ['atlanta'] },
  { name: 'The Deer and The Dove', slug: 'thedeerandthedove', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The White Bull', slug: 'thewhitebull', category: 'restaurant', metros: ['atlanta'] },
  { name: 'LEON\'s Full Service', slug: 'leonsfullservice', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Po\'Boy Shop & Basement Bar', slug: 'thepoboyshopbasementbar', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Parker\'s on Ponce', slug: 'parkersonponce', category: 'restaurant', metros: ['atlanta'] },
  { name: 'no. 246', slug: 'no246', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Murphy\'s Restaurant', slug: 'murphysrestaurant', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Whiskey Bird', slug: 'whiskeybird', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ela', slug: 'ela', category: 'restaurant', metros: ['atlanta'] },
  { name: 'La Tavola Trattoria', slug: 'latavolatrattoria', category: 'italian', metros: ['atlanta'] },
  { name: 'Yeppa & Co. - Buckhead', slug: 'yeppaco-buckhead', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Tiny Lou\'s', slug: 'tinylous', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Fontaine\'s Oyster House', slug: 'fontainesoysterhouse', category: 'seafood', metros: ['atlanta'] },
  { name: 'Argosy', slug: 'argosy', category: 'restaurant', metros: ['atlanta'] },
];

export const BOSTON_RESTAURANTS: RestaurantData[] = [
  { name: 'The Salty Pig', slug: 'thesaltypig', category: 'restaurant', metros: ['boston'] },
  { name: 'Saltie Girl', slug: 'saltiegirl', category: 'restaurant', metros: ['boston'] },
  { name: 'Beehive Restaurant', slug: 'beehiverestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Mamma Maria', slug: 'mammamaria', category: 'restaurant', metros: ['boston'] },
  { name: 'Grill 23 & Bar', slug: 'grill23bar', category: 'restaurant', metros: ['boston'] },
  { name: 'Coquette', slug: 'coquette', category: 'restaurant', metros: ['boston'] },
  { name: 'Atlantic Fish Company', slug: 'atlanticfishcompany', category: 'seafood', metros: ['boston'] },
  { name: 'Boston Sail Loft', slug: 'bostonsailloft', category: 'restaurant', metros: ['boston'] },
  { name: 'Legal Sea Foods - Harborside', slug: 'legalseafoods-harborside', category: 'restaurant', metros: ['boston'] },
  { name: 'Ostra', slug: 'ostra', category: 'restaurant', metros: ['boston'] },
  { name: 'James Hook & Co', slug: 'jameshookco', category: 'restaurant', metros: ['boston'] },
  { name: 'The Oceanaire Seafood Room', slug: 'theoceanaireseafoodroom', category: 'seafood', metros: ['boston'] },
  { name: 'Chart House', slug: 'charthouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Union Oyster House', slug: 'unionoysterhouse', category: 'seafood', metros: ['boston'] },
  { name: 'STK Steakhouse', slug: 'stksteakhouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Wusong Tiki Bar', slug: 'wusongtikibar', category: 'restaurant', metros: ['boston'] },
  { name: 'Highland Kitchen', slug: 'highlandkitchen', category: 'restaurant', metros: ['boston'] },
  { name: 'Carmelina\'s', slug: 'carmelinas', category: 'restaurant', metros: ['boston'] },
  { name: 'La Famiglia Giorgio\'s Restaurant', slug: 'lafamigliagiorgiosrestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Giacomo\'s Boston North End', slug: 'giacomosbostonnorthend', category: 'restaurant', metros: ['boston'] },
  { name: 'Prezza', slug: 'prezza', category: 'restaurant', metros: ['boston'] },
  { name: 'Limoncello', slug: 'limoncello', category: 'restaurant', metros: ['boston'] },
  { name: 'Little Sage', slug: 'littlesage', category: 'restaurant', metros: ['boston'] },
  { name: 'Antico Forno', slug: 'anticoforno', category: 'restaurant', metros: ['boston'] },
  { name: 'Bricco', slug: 'bricco', category: 'restaurant', metros: ['boston'] },
  { name: 'Cantina Italiana', slug: 'cantinaitaliana', category: 'italian', metros: ['boston'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['boston'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['boston'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['boston'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['boston'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['boston'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['boston'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['boston'] },
  { name: 'MIDA', slug: 'mida', category: 'restaurant', metros: ['boston'] },
  { name: 'SRV', slug: 'srv', category: 'restaurant', metros: ['boston'] },
  { name: 'South End Buttery', slug: 'southendbuttery', category: 'restaurant', metros: ['boston'] },
  { name: 'The Elephant Walk South End', slug: 'theelephantwalksouthend', category: 'restaurant', metros: ['boston'] },
  { name: 'The Shawmut Inn', slug: 'theshawmutinn', category: 'restaurant', metros: ['boston'] },
  { name: 'Toro', slug: 'toro', category: 'restaurant', metros: ['boston'] },
  { name: 'Barcelona Wine Bar', slug: 'barcelonawinebar', category: 'restaurant', metros: ['boston'] },
  { name: 'Metropolis', slug: 'metropolis', category: 'restaurant', metros: ['boston'] },
  { name: 'Lulu\'s Allston', slug: 'lulusallston', category: 'restaurant', metros: ['boston'] },
  { name: 'Hopewell Bar & Kitchen', slug: 'hopewellbarkitchen', category: 'restaurant', metros: ['boston'] },
  { name: 'The Stockyard Restaurant', slug: 'thestockyardrestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Brighton Bodega', slug: 'brightonbodega', category: 'restaurant', metros: ['boston'] },
  { name: 'Tasca Restaurant', slug: 'tascarestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Kaju Korean Cuisine — Allston', slug: 'kajukoreancuisineallston', category: 'korean', metros: ['boston'] },
  { name: 'Qiao Lin Hotpot - Boston', slug: 'qiaolinhotpot-boston', category: 'restaurant', metros: ['boston'] },
  { name: 'Seoul Soulongtang', slug: 'seoulsoulongtang', category: 'southern', metros: ['boston'] },
  { name: 'Dumpling Kingdom', slug: 'dumplingkingdom', category: 'chinese', metros: ['boston'] },
  { name: 'Bonchon Allston', slug: 'bonchonallston', category: 'restaurant', metros: ['boston'] },
  { name: 'Myers+Chang', slug: 'myerschang', category: 'restaurant', metros: ['boston'] },
  { name: 'Shōjō Boston', slug: 'shjboston', category: 'restaurant', metros: ['boston'] },
  { name: 'The Q', slug: 'theq', category: 'restaurant', metros: ['boston'] },
  { name: 'Fuchun Ju', slug: 'fuchunju', category: 'restaurant', metros: ['boston'] },
  { name: 'Wa Shin', slug: 'washin', category: 'restaurant', metros: ['boston'] },
  { name: 'JiangNan Boston', slug: 'jiangnanboston', category: 'restaurant', metros: ['boston'] },
  { name: 'Yunnan Kitchen', slug: 'yunnankitchen', category: 'restaurant', metros: ['boston'] },
  { name: 'RUKA', slug: 'ruka', category: 'restaurant', metros: ['boston'] },
  { name: 'KChickin (Korean, Sushi, Hand roll and Japanese Cuisine)', slug: 'kchickinkoreansushihandrollandjapanesecu', category: 'japanese', metros: ['boston'] },
  { name: 'Sarma Restaurant', slug: 'sarmarestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Premiere on Broadway', slug: 'premiereonbroadway', category: 'restaurant', metros: ['boston'] },
  { name: 'Field & Vine', slug: 'fieldvine', category: 'restaurant', metros: ['boston'] },
  { name: 'Civility Social House', slug: 'civilitysocialhouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Foundry On Elm', slug: 'foundryonelm', category: 'restaurant', metros: ['boston'] },
  { name: 'Earls Kitchen + Bar', slug: 'earlskitchenbar', category: 'restaurant', metros: ['boston'] },
  { name: 'Avenue kitchen + bar', slug: 'avenuekitchenbar', category: 'restaurant', metros: ['boston'] },
  { name: 'Salt + Stone', slug: 'saltstone', category: 'restaurant', metros: ['boston'] },
  { name: 'june bug restaurant', slug: 'junebugrestaurant', category: 'restaurant', metros: ['boston'] },
];

export const CHICAGO_RESTAURANTS: RestaurantData[] = [
  { name: 'Girl & The Goat', slug: 'girlthegoat', category: 'restaurant', metros: ['chicago'] },
  { name: 'River Roast', slug: 'riverroast', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Dearborn', slug: 'thedearborn', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Purple Pig Restaurant', slug: 'thepurplepigrestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'Elephant & Castle', slug: 'elephantcastle', category: 'restaurant', metros: ['chicago'] },
  { name: 'Alla Vita', slug: 'allavita', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carnivale Chicago', slug: 'carnivalechicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Beatnik On The River', slug: 'beatnikontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Quartino Ristorante', slug: 'quartinoristorante', category: 'restaurant', metros: ['chicago'] },
  { name: 'Eataly', slug: 'eataly', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pizzeria Portofino', slug: 'pizzeriaportofino', category: 'restaurant', metros: ['chicago'] },
  { name: 'Giordano\'s', slug: 'giordanos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Gino\'s East', slug: 'ginoseast', category: 'restaurant', metros: ['chicago'] },
  { name: 'Zarella Pizzeria & Taverna', slug: 'zarellapizzeriataverna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pequod\'s Pizza', slug: 'pequodspizza', category: 'pizza', metros: ['chicago'] },
  { name: 'Spacca Napoli Pizzeria', slug: 'spaccanapolipizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Lou Malnati\'s Pizzeria', slug: 'loumalnatispizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Robert\'s Pizza and Dough Company', slug: 'robertspizzaanddoughcompany', category: 'pizza', metros: ['chicago'] },
  { name: 'Labriola Ristorante - Chicago', slug: 'labriolaristorante-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Perch Kitchen and Tap', slug: 'theperchkitchenandtap', category: 'restaurant', metros: ['chicago'] },
  { name: 'Big Star Wicker Park', slug: 'bigstarwickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Paradise Park | Pizza & Patio', slug: 'paradiseparkpizzapatio', category: 'pizza', metros: ['chicago'] },
  { name: 'Elia Chicago', slug: 'eliachicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ina Mae', slug: 'inamae', category: 'restaurant', metros: ['chicago'] },
  { name: 'Amaru', slug: 'amaru', category: 'restaurant', metros: ['chicago'] },
  { name: 'Handlebar', slug: 'handlebar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Piece Pizzeria and Brewery', slug: 'piecepizzeriaandbrewery', category: 'restaurant', metros: ['chicago'] },
  { name: 'Cafe Robey', slug: 'caferobey', category: 'cafe', metros: ['chicago'] },
  { name: 'Bangers & Lace Wicker Park', slug: 'bangerslacewickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Summer House Santa Monica', slug: 'summerhousesantamonica', category: 'restaurant', metros: ['chicago'] },
  { name: 'Boka', slug: 'boka', category: 'restaurant', metros: ['chicago'] },
  { name: 'Blue Door Farm Stand', slug: 'bluedoorfarmstand', category: 'restaurant', metros: ['chicago'] },
  { name: 'North Pond', slug: 'northpond', category: 'restaurant', metros: ['chicago'] },
  { name: 'Mon Ami Gabi', slug: 'monamigabi', category: 'restaurant', metros: ['chicago'] },
  { name: 'GEMINI', slug: 'gemini', category: 'restaurant', metros: ['chicago'] },
  { name: 'Armitage Alehouse', slug: 'armitagealehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'DeNucci\'s Lincoln Park', slug: 'denuccislincolnpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Willow Room', slug: 'willowroom', category: 'restaurant', metros: ['chicago'] },
  { name: 'Aba', slug: 'aba', category: 'restaurant', metros: ['chicago'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['chicago'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['chicago'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['chicago'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Café No Sé', slug: 'cafnos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Costera Cocina Tulum - Chicago', slug: 'costeracocinatulum-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ayayay - Mexican Eatery', slug: 'ayayay-mexicaneatery', category: 'mexican', metros: ['chicago'] },
  { name: 'Mercadito', slug: 'mercadito', category: 'restaurant', metros: ['chicago'] },
  { name: 'Casa Tulum', slug: 'casatulum', category: 'restaurant', metros: ['chicago'] },
  { name: 'Tzuco', slug: 'tzuco', category: 'restaurant', metros: ['chicago'] },
  { name: 'Momento Cantina', slug: 'momentocantina', category: 'restaurant', metros: ['chicago'] },
  { name: 'Matilda Restaurant', slug: 'matildarestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'XOCO', slug: 'xoco', category: 'restaurant', metros: ['chicago'] },
  { name: 'La Luna', slug: 'laluna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Frontera Grill', slug: 'fronteragrill', category: 'restaurant', metros: ['chicago'] },
  { name: 'Green Street Smoked Meats', slug: 'greenstreetsmokedmeats', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoque BBQ', slug: 'smoquebbq', category: 'korean', metros: ['chicago'] },
  { name: 'Bub City', slug: 'bubcity', category: 'restaurant', metros: ['chicago'] },
  { name: 'Chubby Cattle BBQ | Chicago', slug: 'chubbycattlebbqchicago', category: 'korean', metros: ['chicago'] },
  { name: 'Offset BBQ', slug: 'offsetbbq', category: 'korean', metros: ['chicago'] },
  { name: 'Honky Tonk BBQ / The Tonk', slug: 'honkytonkbbqthetonk', category: 'korean', metros: ['chicago'] },
  { name: 'Chicago Q', slug: 'chicagoq', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carson’s Prime Steaks & Famous Barbecue – Chicago (Streeterville)', slug: 'carsonsprimesteaksfamousbarbecuechicagos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Soul & Smoke - Avondale at Rockwell on the River', slug: 'soulsmoke-avondaleatrockwellontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoke Daddy BBQ - Wrigleyville', slug: 'smokedaddybbq-wrigleyville', category: 'korean', metros: ['chicago'] },
  { name: 'Union', slug: 'union', category: 'restaurant', metros: ['chicago'] },
  { name: 'Fuego Logan Square', slug: 'fuegologansquare', category: 'restaurant', metros: ['chicago'] },
  { name: 'Scofflaw', slug: 'scofflaw', category: 'restaurant', metros: ['chicago'] },
  { name: 'Gretel', slug: 'gretel', category: 'restaurant', metros: ['chicago'] },
  { name: 'Daisies', slug: 'daisies', category: 'restaurant', metros: ['chicago'] },
  { name: 'Table, Donkey and Stick', slug: 'tabledonkeyandstick', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Duplex', slug: 'theduplex', category: 'restaurant', metros: ['chicago'] },
  { name: 'Lula Cafe', slug: 'lulacafe', category: 'cafe', metros: ['chicago'] },
  { name: 'The Whale', slug: 'thewhale', category: 'restaurant', metros: ['chicago'] },
  { name: 'Longman & Eagle', slug: 'longmaneagle', category: 'restaurant', metros: ['chicago'] },
  { name: 'RAMEN-SAN', slug: 'ramen-san', category: 'japanese', metros: ['chicago'] },
  { name: 'RPM Seafood', slug: 'rpmseafood', category: 'seafood', metros: ['chicago'] },
  { name: 'Obélix', slug: 'oblix', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Izakaya', slug: 'theizakaya', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Oakville Grill & Cellar', slug: 'theoakvillegrillcellar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Monteverde Restaurant & Pastificio', slug: 'monteverderestaurantpastificio', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Publican', slug: 'thepublican', category: 'restaurant', metros: ['chicago'] },
  { name: 'The VIG West Loop', slug: 'thevigwestloop', category: 'restaurant', metros: ['chicago'] },
  { name: 'Duck Duck Goat', slug: 'duckduckgoat', category: 'restaurant', metros: ['chicago'] },
  { name: 'La Serre', slug: 'laserre', category: 'restaurant', metros: ['chicago'] },
  { name: 'Rubi’s Tacos', slug: 'rubistacos', category: 'mexican', metros: ['chicago'] },
  { name: 'La Vaca Margarita Bar', slug: 'lavacamargaritabar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ramen Wasabi - Logan Square', slug: 'ramenwasabi-logansquare', category: 'japanese', metros: ['chicago'] },
  { name: 'High Five Ramen', slug: 'highfiveramen', category: 'japanese', metros: ['chicago'] },
  { name: 'Birdman Ramen', slug: 'birdmanramen', category: 'japanese', metros: ['chicago'] },
  { name: 'CHICAGO RAMEN', slug: 'chicagoramen', category: 'japanese', metros: ['chicago'] },
  { name: 'Kyuramen x TBaar - Downtown Chicago', slug: 'kyuramenxtbaar-downtownchicago', category: 'japanese', metros: ['chicago'] },
  { name: 'Rudy\'s Ramen', slug: 'rudysramen', category: 'japanese', metros: ['chicago'] },
  { name: 'MIKAMI IZAKAYA & RAMEN', slug: 'mikamiizakayaramen', category: 'japanese', metros: ['chicago'] },
  { name: 'Ramen-San Lincoln Park', slug: 'ramen-sanlincolnpark', category: 'japanese', metros: ['chicago'] },
  { name: 'RAMEN-SAN Deluxe', slug: 'ramen-sandeluxe', category: 'japanese', metros: ['chicago'] },
  { name: 'India House Restaurant Chicago', slug: 'indiahouserestaurantchicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Indian Garden Restaurant', slug: 'indiangardenrestaurant', category: 'indian', metros: ['chicago'] },
  { name: 'Maharaj Indian Grill', slug: 'maharajindiangrill', category: 'indian', metros: ['chicago'] },
  { name: 'Chicago Curry House - Indian - Nepali Cuisine.', slug: 'chicagocurryhouse-indian-nepalicuisine', category: 'indian', metros: ['chicago'] },
  { name: 'Indienne', slug: 'indienne', category: 'restaurant', metros: ['chicago'] },
  { name: 'Bar Goa', slug: 'bargoa', category: 'restaurant', metros: ['chicago'] },
  { name: 'Mild 2 Spicy – Modern Indian Restaurant', slug: 'mild2spicymodernindianrestaurant', category: 'indian', metros: ['chicago'] },
  { name: 'ROOP Chicago Innovative Indian Restaurant & Cocktail Bar', slug: 'roopchicagoinnovativeindianrestaurantcoc', category: 'indian', metros: ['chicago'] },
  { name: 'Basant Modern Indian Restaurant', slug: 'basantmodernindianrestaurant', category: 'indian', metros: ['chicago'] },
  { name: 'Siri Indian Restaurant', slug: 'siriindianrestaurant', category: 'indian', metros: ['chicago'] },
  { name: 'Crying Tiger', slug: 'cryingtiger', category: 'restaurant', metros: ['chicago'] },
  { name: 'Madame Puffs and Thai Bistro', slug: 'madamepuffsandthaibistro', category: 'thai', metros: ['chicago'] },
  { name: 'Oliang', slug: 'oliang', category: 'restaurant', metros: ['chicago'] },
  { name: 'Anna\'s Thai Kitchen Restaurant', slug: 'annasthaikitchenrestaurant', category: 'thai', metros: ['chicago'] },
  { name: 'Busaba Garden Thai Cuisine', slug: 'busabagardenthaicuisine', category: 'thai', metros: ['chicago'] },
  { name: 'Ghin Khao Eat Rice', slug: 'ghinkhaoeatrice', category: 'restaurant', metros: ['chicago'] },
  { name: 'Immm Rice & Beyond', slug: 'immmricebeyond', category: 'restaurant', metros: ['chicago'] },
  { name: 'Tuk Tuk Thai Isan Street Food', slug: 'tuktukthaiisanstreetfood', category: 'thai', metros: ['chicago'] },
  { name: 'Curry Blah Blah', slug: 'curryblahblah', category: 'indian', metros: ['chicago'] },
  { name: 'Mahanakhon Thai & Noodle Bar', slug: 'mahanakhonthainoodlebar', category: 'thai', metros: ['chicago'] },
  { name: 'Little Goat Diner', slug: 'littlegoatdiner', category: 'restaurant', metros: ['chicago'] },
  { name: 'Crosby\'s Kitchen', slug: 'crosbyskitchen', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Lakefront Restaurant at Theater on the Lake', slug: 'thelakefrontrestaurantattheateronthelake', category: 'restaurant', metros: ['chicago'] },
  { name: 'UncommonGround - Lakeview', slug: 'uncommonground-lakeview', category: 'restaurant', metros: ['chicago'] },
  { name: 'Coda di Volpe', slug: 'codadivolpe', category: 'restaurant', metros: ['chicago'] },
  { name: 'Old Crow Smokehouse', slug: 'oldcrowsmokehouse', category: 'bbq', metros: ['chicago'] },
  { name: 'ROCKS lakeview', slug: 'rockslakeview', category: 'restaurant', metros: ['chicago'] },
  { name: 'MingHin Cuisine', slug: 'minghincuisine', category: 'restaurant', metros: ['chicago'] },
  { name: 'Qing Xiang Yuan Dumplings', slug: 'qingxiangyuandumplings', category: 'chinese', metros: ['chicago'] },
  { name: 'Bigsuda', slug: 'bigsuda', category: 'restaurant', metros: ['chicago'] },
  { name: 'Triple Crown Restaurant', slug: 'triplecrownrestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'Phoenix Restaurant', slug: 'phoenixrestaurant', category: 'vietnamese', metros: ['chicago'] },
  { name: 'Dolo Restaurant and Bar', slug: 'dolorestaurantandbar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Union Dumpling House', slug: 'uniondumplinghouse', category: 'chinese', metros: ['chicago'] },
  { name: 'MingHin Cuisine - Lakeshore East', slug: 'minghincuisine-lakeshoreeast', category: 'restaurant', metros: ['chicago'] },
  { name: 'Minghin Cuisine - Streeterville', slug: 'minghincuisine-streeterville', category: 'restaurant', metros: ['chicago'] },
];

export const DENVER_RESTAURANTS: RestaurantData[] = [
  { name: 'The Plimoth', slug: 'theplimoth', category: 'restaurant', metros: ['denver'] },
  { name: 'The Denver Central Market', slug: 'thedenvercentralmarket', category: 'restaurant', metros: ['denver'] },
  { name: 'Temaki Den', slug: 'temakiden', category: 'restaurant', metros: ['denver'] },
  { name: 'Point Easy Denver', slug: 'pointeasydenver', category: 'restaurant', metros: ['denver'] },
  { name: 'major tom', slug: 'majortom', category: 'restaurant', metros: ['denver'] },
  { name: 'Federales Tacos & Tequila - RiNo, Denver', slug: 'federalestacostequila-rinodenver', category: 'mexican', metros: ['denver'] },
  { name: 'Alma Fonda Fina', slug: 'almafondafina', category: 'restaurant', metros: ['denver'] },
  { name: 'Nocturne', slug: 'nocturne', category: 'restaurant', metros: ['denver'] },
  { name: 'Cart-Driver RiNo', slug: 'cart-driverrino', category: 'restaurant', metros: ['denver'] },
  { name: 'Work & Class', slug: 'workclass', category: 'restaurant', metros: ['denver'] },
  { name: 'BearLeek', slug: 'bearleek', category: 'restaurant', metros: ['denver'] },
  { name: 'Linger', slug: 'linger', category: 'restaurant', metros: ['denver'] },
  { name: 'The Hampton Social - Denver', slug: 'thehamptonsocial-denver', category: 'restaurant', metros: ['denver'] },
  { name: 'Wildflower', slug: 'wildflower', category: 'restaurant', metros: ['denver'] },
  { name: 'Fox And The Hen', slug: 'foxandthehen', category: 'restaurant', metros: ['denver'] },
  { name: 'Postino LoHi', slug: 'postinolohi', category: 'restaurant', metros: ['denver'] },
  { name: 'Mezcaleria Alma', slug: 'mezcaleriaalma', category: 'restaurant', metros: ['denver'] },
  { name: 'Sassafras American Eatery, Highlands', slug: 'sassafrasamericaneateryhighlands', category: 'restaurant', metros: ['denver'] },
  { name: 'Corinne Denver', slug: 'corinnedenver', category: 'restaurant', metros: ['denver'] },
  { name: 'Bar Dough', slug: 'bardough', category: 'restaurant', metros: ['denver'] },
  { name: 'Salt Water Social', slug: 'saltwatersocial', category: 'restaurant', metros: ['denver'] },
  { name: 'Cherry Creek Grill', slug: 'cherrycreekgrill', category: 'restaurant', metros: ['denver'] },
  { name: 'Kona Grill - Denver', slug: 'konagrill-denver', category: 'restaurant', metros: ['denver'] },
  { name: 'Hillstone', slug: 'hillstone', category: 'restaurant', metros: ['denver'] },
  { name: 'The Cherry Cricket', slug: 'thecherrycricket', category: 'restaurant', metros: ['denver'] },
  { name: 'North Italia', slug: 'northitalia', category: 'restaurant', metros: ['denver'] },
  { name: 'True Food Kitchen', slug: 'truefoodkitchen', category: 'restaurant', metros: ['denver'] },
  { name: 'Culinary Dropout', slug: 'culinarydropout', category: 'restaurant', metros: ['denver'] },
  { name: 'Narrative', slug: 'narrative', category: 'restaurant', metros: ['denver'] },
  { name: 'Barolo Grill', slug: 'barologrill', category: 'restaurant', metros: ['denver'] },
];

export const HOUSTON_RESTAURANTS: RestaurantData[] = [
  { name: 'Lost & Found', slug: 'lostfound', category: 'restaurant', metros: ['houston'] },
  { name: 'Aquarium Restaurant', slug: 'aquariumrestaurant', category: 'restaurant', metros: ['houston'] },
  { name: 'Bungalow', slug: 'bungalow', category: 'restaurant', metros: ['houston'] },
  { name: 'State of Grace', slug: 'stateofgrace', category: 'restaurant', metros: ['houston'] },
  { name: 'Lucille\'s', slug: 'lucilles', category: 'restaurant', metros: ['houston'] },
  { name: 'Brenner\'s on the Bayou', slug: 'brennersonthebayou', category: 'restaurant', metros: ['houston'] },
  { name: 'Hull & Oak', slug: 'hulloak', category: 'restaurant', metros: ['houston'] },
  { name: 'Traveler\'s Table', slug: 'travelerstable', category: 'restaurant', metros: ['houston'] },
  { name: 'Taste of Texas', slug: 'tasteoftexas', category: 'restaurant', metros: ['houston'] },
  { name: 'JOEY Uptown', slug: 'joeyuptown', category: 'restaurant', metros: ['houston'] },
  { name: 'Postino Montrose', slug: 'postinomontrose', category: 'restaurant', metros: ['houston'] },
  { name: 'The Pit Room', slug: 'thepitroom', category: 'restaurant', metros: ['houston'] },
  { name: 'Fielding\'s Steak', slug: 'fieldingssteak', category: 'restaurant', metros: ['houston'] },
  { name: 'Roost', slug: 'roost', category: 'restaurant', metros: ['houston'] },
  { name: 'Little’s Oyster Bar', slug: 'littlesoysterbar', category: 'seafood', metros: ['houston'] },
  { name: 'Nobie\'s', slug: 'nobies', category: 'restaurant', metros: ['houston'] },
  { name: '93\' Til', slug: '93til', category: 'restaurant', metros: ['houston'] },
  { name: 'Hugo\'s', slug: 'hugos', category: 'restaurant', metros: ['houston'] },
  { name: 'La Lucha', slug: 'lalucha', category: 'restaurant', metros: ['houston'] },
  { name: 'Squable', slug: 'squable', category: 'restaurant', metros: ['houston'] },
  { name: 'Field & Tides', slug: 'fieldtides', category: 'restaurant', metros: ['houston'] },
  { name: 'Postino Heights', slug: 'postinoheights', category: 'restaurant', metros: ['houston'] },
  { name: 'Pinkerton\'s Barbecue', slug: 'pinkertonsbarbecue', category: 'bbq', metros: ['houston'] },
  { name: 'Moon Rabbit', slug: 'moonrabbit', category: 'restaurant', metros: ['houston'] },
  { name: 'Jūn', slug: 'jn', category: 'restaurant', metros: ['houston'] },
  { name: 'Blue Tuba', slug: 'bluetuba', category: 'restaurant', metros: ['houston'] },
  { name: 'Better Luck Tomorrow', slug: 'betterlucktomorrow', category: 'restaurant', metros: ['houston'] },
  { name: 'Gotti\'s', slug: 'gottis', category: 'restaurant', metros: ['houston'] },
  { name: 'Nancy\'s Hustle', slug: 'nancyshustle', category: 'restaurant', metros: ['houston'] },
  { name: 'Truck Yard', slug: 'truckyard', category: 'restaurant', metros: ['houston'] },
  { name: 'Rodeo Goat', slug: 'rodeogoat', category: 'restaurant', metros: ['houston'] },
  { name: 'Grotto Downtown', slug: 'grottodowntown', category: 'restaurant', metros: ['houston'] },
  { name: 'Tiny Champions', slug: 'tinychampions', category: 'restaurant', metros: ['houston'] },
  { name: 'Huynh Restaurant', slug: 'huynhrestaurant', category: 'restaurant', metros: ['houston'] },
  { name: 'Annam Vietnamese Restaurant', slug: 'annamvietnameserestaurant', category: 'vietnamese', metros: ['houston'] },
  { name: 'Le Colonial Houston', slug: 'lecolonialhouston', category: 'restaurant', metros: ['houston'] },
  { name: 'Mai\'s Restaurant', slug: 'maisrestaurant', category: 'restaurant', metros: ['houston'] },
  { name: 'LES BA\'GET Vietnamese Cafe', slug: 'lesbagetvietnamesecafe', category: 'cafe', metros: ['houston'] },
  { name: 'Lúa Viet Kitchen', slug: 'lavietkitchen', category: 'restaurant', metros: ['houston'] },
  { name: 'Old Saigon Cafe', slug: 'oldsaigoncafe', category: 'cafe', metros: ['houston'] },
  { name: 'Hughie\'s Tavern & Viet Grill', slug: 'hughiestavernvietgrill', category: 'restaurant', metros: ['houston'] },
  { name: 'Yummy Quan - Hu Tieu Nam Vang', slug: 'yummyquan-hutieunamvang', category: 'restaurant', metros: ['houston'] },
  { name: 'Pearl & Vine', slug: 'pearlvine', category: 'restaurant', metros: ['houston'] },
  { name: 'Local Table', slug: 'localtable', category: 'restaurant', metros: ['houston'] },
  { name: 'Texas Tradition', slug: 'texastradition', category: 'restaurant', metros: ['houston'] },
  { name: 'Whiskey Cake Kitchen & Bar', slug: 'whiskeycakekitchenbar', category: 'restaurant', metros: ['houston'] },
  { name: 'Black Bear Diner Katy', slug: 'blackbeardinerkaty', category: 'restaurant', metros: ['houston'] },
  { name: 'Little Italy Restaurant', slug: 'littleitalyrestaurant', category: 'restaurant', metros: ['houston'] },
  { name: 'Postino Cinco Ranch', slug: 'postinocincoranch', category: 'restaurant', metros: ['houston'] },
  { name: 'Astor\'s Table', slug: 'astorstable', category: 'restaurant', metros: ['houston'] },
  { name: 'Katy Asian Town', slug: 'katyasiantown', category: 'restaurant', metros: ['houston'] },
  { name: 'Katy Vibes', slug: 'katyvibes', category: 'restaurant', metros: ['houston'] },
];

export const LA_RESTAURANTS: RestaurantData[] = [
  { name: 'Perch', slug: 'perch', category: 'restaurant', metros: ['la'] },
  { name: 'JOEY DTLA', slug: 'joeydtla', category: 'restaurant', metros: ['la'] },
  { name: 'Little Beast Restaurant', slug: 'littlebeastrestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Yamashiro Hollywood', slug: 'yamashirohollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Musso & Frank Grill', slug: 'mussofrankgrill', category: 'restaurant', metros: ['la'] },
  { name: 'Providence', slug: 'providence', category: 'restaurant', metros: ['la'] },
  { name: 'La Boheme', slug: 'laboheme', category: 'restaurant', metros: ['la'] },
  { name: 'Superba Food + Bread Hollywood', slug: 'superbafoodbreadhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'The Little Door', slug: 'thelittledoor', category: 'restaurant', metros: ['la'] },
  { name: 'Girl & the Goat Los Angeles', slug: 'girlthegoatlosangeles', category: 'restaurant', metros: ['la'] },
  { name: 'Jemma Hollywood', slug: 'jemmahollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Running Goose', slug: 'runninggoose', category: 'restaurant', metros: ['la'] },
  { name: 'Mother Wolf', slug: 'motherwolf', category: 'restaurant', metros: ['la'] },
  { name: 'UOVO Santa Monica', slug: 'uovosantamonica', category: 'restaurant', metros: ['la'] },
  { name: 'Guelaguetza Restaurant', slug: 'guelaguetzarestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Holbox', slug: 'holbox', category: 'restaurant', metros: ['la'] },
  { name: 'El Cholo - The Original', slug: 'elcholo-theoriginal', category: 'restaurant', metros: ['la'] },
  { name: 'Guisados', slug: 'guisados', category: 'restaurant', metros: ['la'] },
  { name: 'Sol Agave LA LIVE', slug: 'solagavelalive', category: 'restaurant', metros: ['la'] },
  { name: 'Gracias Madre', slug: 'graciasmadre', category: 'restaurant', metros: ['la'] },
  { name: 'El Compadre Restaurant of Hollywood', slug: 'elcompadrerestaurantofhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Casita Del Campo', slug: 'casitadelcampo', category: 'restaurant', metros: ['la'] },
  { name: 'Javier\'s', slug: 'javiers', category: 'restaurant', metros: ['la'] },
  { name: 'Madre Restaurant', slug: 'madrerestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Hae Jang Chon Korean BBQ Restaurant', slug: 'haejangchonkoreanbbqrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Sun Nong Dan', slug: 'sunnongdan', category: 'restaurant', metros: ['la'] },
  { name: 'Jumsim', slug: 'jumsim', category: 'restaurant', metros: ['la'] },
  { name: 'Hanu K BBQ', slug: 'hanukbbq', category: 'korean', metros: ['la'] },
  { name: 'Park\'s BBQ', slug: 'parksbbq', category: 'korean', metros: ['la'] },
  { name: 'Jun Won Dak IG @junwon_la', slug: 'junwondakigjunwonla', category: 'restaurant', metros: ['la'] },
  { name: 'Kobawoo House', slug: 'kobawoohouse', category: 'restaurant', metros: ['la'] },
  { name: 'HOJOKBAN LA', slug: 'hojokbanla', category: 'restaurant', metros: ['la'] },
  { name: '여기요 YeoGiYo 한식전문 | Premium Korean Restaurant', slug: 'yeogiyopremiumkoreanrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Baroo', slug: 'baroo', category: 'restaurant', metros: ['la'] },
  { name: 'Bacari Silverlake', slug: 'bacarisilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Sonmari', slug: 'sonmari', category: 'restaurant', metros: ['la'] },
  { name: 'Pine and Crane Silverlake', slug: 'pineandcranesilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Botanica Restaurant and Market', slug: 'botanicarestaurantandmarket', category: 'restaurant', metros: ['la'] },
  { name: 'Izakaya Osen', slug: 'izakayaosen', category: 'restaurant', metros: ['la'] },
  { name: 'Tacolina', slug: 'tacolina', category: 'mexican', metros: ['la'] },
  { name: 'Ceviche Project', slug: 'cevicheproject', category: 'restaurant', metros: ['la'] },
  { name: 'The Black Cat', slug: 'theblackcat', category: 'restaurant', metros: ['la'] },
  { name: 'Santo Silverlake', slug: 'santosilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Belles Beach House', slug: 'bellesbeachhouse', category: 'restaurant', metros: ['la'] },
  { name: 'The Waterfront Venice', slug: 'thewaterfrontvenice', category: 'restaurant', metros: ['la'] },
  { name: 'Si! Mon', slug: 'simon', category: 'restaurant', metros: ['la'] },
  { name: 'Felix Trattoria', slug: 'felixtrattoria', category: 'italian', metros: ['la'] },
  { name: 'The Butcher\'s Daughter', slug: 'thebutchersdaughter', category: 'restaurant', metros: ['la'] },
  { name: 'Paloma Venice', slug: 'palomavenice', category: 'restaurant', metros: ['la'] },
  { name: 'Barrique Venice', slug: 'barriquevenice', category: 'restaurant', metros: ['la'] },
  { name: 'Great White', slug: 'greatwhite', category: 'restaurant', metros: ['la'] },
  { name: 'Ospi Venice', slug: 'ospivenice', category: 'restaurant', metros: ['la'] },
  { name: 'Beachside Restaurant & Bar', slug: 'beachsiderestaurantbar', category: 'restaurant', metros: ['la'] },
  { name: '71Above', slug: '71above', category: 'restaurant', metros: ['la'] },
  { name: 'Bottega Louie', slug: 'bottegalouie', category: 'restaurant', metros: ['la'] },
  { name: 'Maccheroni Republic', slug: 'maccheronirepublic', category: 'restaurant', metros: ['la'] },
  { name: 'Rossoblu', slug: 'rossoblu', category: 'restaurant', metros: ['la'] },
  { name: 'Manuela', slug: 'manuela', category: 'restaurant', metros: ['la'] },
  { name: 'Fleming’s Prime Steakhouse & Wine Bar', slug: 'flemingsprimesteakhousewinebar', category: 'steakhouse', metros: ['la'] },
  { name: 'Eggslut', slug: 'eggslut', category: 'restaurant', metros: ['la'] },
  { name: 'Jitlada Restaurant', slug: 'jitladarestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Spelling Thai Bistro', slug: 'spellingthaibistro', category: 'thai', metros: ['la'] },
  { name: 'SAOHA KHAO SOI THAI CUISINE', slug: 'saohakhaosoithaicuisine', category: 'thai', metros: ['la'] },
  { name: 'Civilize Thai Bistro', slug: 'civilizethaibistro', category: 'thai', metros: ['la'] },
  { name: 'Farmhouse Kitchen Thai Cuisine LA', slug: 'farmhousekitchenthaicuisinela', category: 'thai', metros: ['la'] },
  { name: 'Ruen Pair', slug: 'ruenpair', category: 'restaurant', metros: ['la'] },
  { name: 'Amphai Northern Thai Food Club', slug: 'amphainorthernthaifoodclub', category: 'thai', metros: ['la'] },
  { name: 'Luv2eat Thai Bistro', slug: 'luv2eatthaibistro', category: 'thai', metros: ['la'] },
  { name: 'Nong\'s Thai Kitchen', slug: 'nongsthaikitchen', category: 'thai', metros: ['la'] },
  { name: 'Lacha Somtum', slug: 'lachasomtum', category: 'restaurant', metros: ['la'] },
  { name: 'Laurel Grill', slug: 'laurelgrill', category: 'restaurant', metros: ['la'] },
  { name: 'Meet in Paris French Bistro', slug: 'meetinparisfrenchbistro', category: 'french', metros: ['la'] },
  { name: 'Maple Block Meat Co.', slug: 'mapleblockmeatco', category: 'restaurant', metros: ['la'] },
  { name: 'Metro Cafe', slug: 'metrocafe', category: 'cafe', metros: ['la'] },
  { name: 'Pasta Sisters', slug: 'pastasisters', category: 'italian', metros: ['la'] },
  { name: 'Margot', slug: 'margot', category: 'restaurant', metros: ['la'] },
  { name: 'Simonette Restaurant', slug: 'simonetterestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'JULIET', slug: 'juliet', category: 'restaurant', metros: ['la'] },
  { name: 'Bianca', slug: 'bianca', category: 'restaurant', metros: ['la'] },
  { name: 'Hey, Sunshine Kitchen', slug: 'heysunshinekitchen', category: 'restaurant', metros: ['la'] },
  { name: 'Tsujita LA Artisan Noodles', slug: 'tsujitalaartisannoodles', category: 'restaurant', metros: ['la'] },
  { name: 'Tatsu Ramen', slug: 'tatsuramen', category: 'japanese', metros: ['la'] },
  { name: 'REDWHITE BONELESS RAMEN', slug: 'redwhitebonelessramen', category: 'japanese', metros: ['la'] },
  { name: 'Daikokuya Little Tokyo', slug: 'daikokuyalittletokyo', category: 'restaurant', metros: ['la'] },
  { name: 'Hinodeya Ramen Bar Little Tokyo', slug: 'hinodeyaramenbarlittletokyo', category: 'japanese', metros: ['la'] },
  { name: 'MENSHO TOKYO', slug: 'menshotokyo', category: 'restaurant', metros: ['la'] },
  { name: 'Hinodeya Ramen Palms', slug: 'hinodeyaramenpalms', category: 'japanese', metros: ['la'] },
  { name: 'AFURI', slug: 'afuri', category: 'restaurant', metros: ['la'] },
  { name: 'Koi Kaze Ramen Bar', slug: 'koikazeramenbar', category: 'japanese', metros: ['la'] },
  { name: 'Bacetti Trattoria', slug: 'bacettitrattoria', category: 'italian', metros: ['la'] },
  { name: 'Donna\'s', slug: 'donnas', category: 'restaurant', metros: ['la'] },
  { name: 'Sticky Rice, Echo Park', slug: 'stickyriceechopark', category: 'restaurant', metros: ['la'] },
  { name: 'Masa of Echo Park Bakery & Cafe', slug: 'masaofechoparkbakerycafe', category: 'cafe', metros: ['la'] },
  { name: 'DADA ECHO PARK', slug: 'dadaechopark', category: 'restaurant', metros: ['la'] },
  { name: 'Larchmont Bungalow Cafe', slug: 'larchmontbungalowcafe', category: 'cafe', metros: ['la'] },
  { name: 'OTOTO', slug: 'ototo', category: 'restaurant', metros: ['la'] },
  { name: 'Honey Hi', slug: 'honeyhi', category: 'restaurant', metros: ['la'] },
  { name: 'Quarter Sheets', slug: 'quartersheets', category: 'restaurant', metros: ['la'] },
  { name: 'Water Grill', slug: 'watergrill', category: 'restaurant', metros: ['la'] },
  { name: 'L.A. CRAZY CRAB', slug: 'lacrazycrab', category: 'restaurant', metros: ['la'] },
  { name: 'Fisherman\'s Outlet', slug: 'fishermansoutlet', category: 'seafood', metros: ['la'] },
  { name: 'San Pedro Fish Market and Restaurant', slug: 'sanpedrofishmarketandrestaurant', category: 'seafood', metros: ['la'] },
  { name: 'Catch', slug: 'catch', category: 'restaurant', metros: ['la'] },
  { name: 'Salt & Pearl', slug: 'saltpearl', category: 'restaurant', metros: ['la'] },
  { name: 'Smackem\' Cajun Seafood', slug: 'smackemcajunseafood', category: 'seafood', metros: ['la'] },
  { name: 'Malibu Seafood', slug: 'malibuseafood', category: 'seafood', metros: ['la'] },
  { name: 'The Raymond 1886 - Modern American Cuisine & Craft Cocktails in Pasadena', slug: 'theraymond1886-modernamericancuisinecraf', category: 'restaurant', metros: ['la'] },
  { name: 'Houston\'s', slug: 'houstons', category: 'restaurant', metros: ['la'] },
  { name: 'GRANVILLE', slug: 'granville', category: 'restaurant', metros: ['la'] },
  { name: 'Nick\'s Pasadena', slug: 'nickspasadena', category: 'restaurant', metros: ['la'] },
  { name: 'Mi Piace', slug: 'mipiace', category: 'restaurant', metros: ['la'] },
  { name: 'Fogo de Chão Brazilian Steakhouse', slug: 'fogodechobraziliansteakhouse', category: 'steakhouse', metros: ['la'] },
  { name: 'Agnes Restaurant & Cheesery', slug: 'agnesrestaurantcheesery', category: 'restaurant', metros: ['la'] },
  { name: 'Cafe Santorini', slug: 'cafesantorini', category: 'cafe', metros: ['la'] },
  { name: 'The Arbour', slug: 'thearbour', category: 'restaurant', metros: ['la'] },
  { name: 'Russell\'s', slug: 'russells', category: 'restaurant', metros: ['la'] },
  { name: 'Phở 87', slug: 'ph87', category: 'restaurant', metros: ['la'] },
  { name: 'NAM Kitchen', slug: 'namkitchen', category: 'restaurant', metros: ['la'] },
  { name: 'Twenty Pho Hour LA', slug: 'twentyphohourla', category: 'vietnamese', metros: ['la'] },
  { name: 'Bé Ù - Vietnamese Street Food & Comfort Food', slug: 'b-vietnamesestreetfoodcomfortfood', category: 'vietnamese', metros: ['la'] },
  { name: 'Goi Vietnamese Eats', slug: 'goivietnameseeats', category: 'vietnamese', metros: ['la'] },
  { name: 'Pho Byob By ktownpho', slug: 'phobyobbyktownpho', category: 'vietnamese', metros: ['la'] },
  { name: 'Pho Saigon Pearl', slug: 'phosaigonpearl', category: 'vietnamese', metros: ['la'] },
  { name: 'Saigon Dish Vietnamese Restaurant', slug: 'saigondishvietnameserestaurant', category: 'vietnamese', metros: ['la'] },
  { name: 'KTOWN PHO', slug: 'ktownpho', category: 'vietnamese', metros: ['la'] },
];

export const MIAMI_RESTAURANTS: RestaurantData[] = [
  { name: 'Komodo Miami', slug: 'komodomiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Moxies Miami Restaurant', slug: 'moxiesmiamirestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Tua Cucina Brickell', slug: 'casatuacucinabrickell', category: 'restaurant', metros: ['miami'] },
  { name: 'Nikki Beach Miami Beach', slug: 'nikkibeachmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Old\'s Havana Cuban Bar & Cocina', slug: 'oldshavanacubanbarcocina', category: 'restaurant', metros: ['miami'] },
  { name: 'Versailles Restaurant Cuban Cuisine', slug: 'versaillesrestaurantcubancuisine', category: 'restaurant', metros: ['miami'] },
  { name: 'La Mulata | Cuban Restaurant Miami Beach', slug: 'lamulatacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Esquina Cubana | Cuban Restaurant Miami Beach', slug: 'esquinacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Havana Vieja | Latin Restaurant Miami Beach', slug: 'havanaviejalatinrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Sala\'o Cuban Restaurant & Bar - Live music', slug: 'salaocubanrestaurantbar-livemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Marabu Restaurant', slug: 'maraburestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Alma Cubana | Cuban Restaurant Miami Beach', slug: 'almacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Cubana | Restaurant & Live Music', slug: 'casacubanarestaurantlivemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Little Havana', slug: 'littlehavana', category: 'restaurant', metros: ['miami'] },
  { name: 'Mayami Wynwood', slug: 'mayamiwynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'Sha Wynwood', slug: 'shawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'R House Wynwood', slug: 'rhousewynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'BAKAN', slug: 'bakan', category: 'restaurant', metros: ['miami'] },
  { name: 'Astra Miami Rooftop', slug: 'astramiamirooftop', category: 'restaurant', metros: ['miami'] },
  { name: 'Le Chick Miami', slug: 'lechickmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Ossobuco Miami - Steak house', slug: 'ossobucomiami-steakhouse', category: 'restaurant', metros: ['miami'] },
  { name: 'KYU Miami', slug: 'kyumiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Manta Wynwood', slug: 'mantawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'MIAM CAFE-WYNWOOD', slug: 'miamcafe-wynwood', category: 'cafe', metros: ['miami'] },
  { name: 'Joe\'s Stone Crab', slug: 'joesstonecrab', category: 'restaurant', metros: ['miami'] },
  { name: 'Mercato della Pescheria Miami Beach', slug: 'mercatodellapescheriamiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Españolita Miami Beach 🌹💃SEAFOOD&STEAKHOUSE', slug: 'espaolitamiamibeachseafoodsteakhouse', category: 'seafood', metros: ['miami'] },
  { name: 'Nettuno Italian Seafood & Oysters', slug: 'nettunoitalianseafoodoysters', category: 'seafood', metros: ['miami'] },
  { name: 'A Fish Called Avalon', slug: 'afishcalledavalon', category: 'seafood', metros: ['miami'] },
  { name: 'CORALLO 🇮🇹 Amalfi coast', slug: 'coralloamalficoast', category: 'restaurant', metros: ['miami'] },
  { name: 'Rusty Pelican Miami', slug: 'rustypelicanmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'CVI.CHE 105 South Beach', slug: 'cviche105southbeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Osteria Positano', slug: 'osteriapositano', category: 'restaurant', metros: ['miami'] },
  { name: 'CJ\'s Crab Shack', slug: 'cjscrabshack', category: 'restaurant', metros: ['miami'] },
  { name: 'Felice Brickell', slug: 'felicebrickell', category: 'restaurant', metros: ['miami'] },
  { name: 'Ciao Havana', slug: 'ciaohavana', category: 'restaurant', metros: ['miami'] },
  { name: 'Sanguich', slug: 'sanguich', category: 'restaurant', metros: ['miami'] },
  { name: 'El Toro Loco Steakhouse Little Havana', slug: 'eltorolocosteakhouselittlehavana', category: 'steakhouse', metros: ['miami'] },
  { name: 'CRAFT Little Havana', slug: 'craftlittlehavana', category: 'restaurant', metros: ['miami'] },
  { name: 'Cafe La Trova', slug: 'cafelatrova', category: 'cafe', metros: ['miami'] },
  { name: 'BALL & CHAIN', slug: 'ballchain', category: 'restaurant', metros: ['miami'] },
  { name: 'Cebada Rooftop', slug: 'cebadarooftop', category: 'restaurant', metros: ['miami'] },
  { name: 'Sofia Italian Restaurant Miami', slug: 'sofiaitalianrestaurantmiami', category: 'italian', metros: ['miami'] },
  { name: 'Giselle Miami', slug: 'gisellemiami', category: 'restaurant', metros: ['miami'] },
  { name: 'COTE Miami', slug: 'cotemiami', category: 'restaurant', metros: ['miami'] },
  { name: '{petite} maman', slug: 'petitemaman', category: 'restaurant', metros: ['miami'] },
  { name: 'Elastika', slug: 'elastika', category: 'restaurant', metros: ['miami'] },
  { name: 'Mother Wolf', slug: 'motherwolf', category: 'restaurant', metros: ['miami'] },
  { name: 'Michael\'s Genuine', slug: 'michaelsgenuine', category: 'restaurant', metros: ['miami'] },
  { name: 'ZOI Restaurant & Lounge', slug: 'zoirestaurantlounge', category: 'restaurant', metros: ['miami'] },
  { name: 'Sola Miami Beach', slug: 'solamiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'El Patio Restaurant – Bar Habana – La Terraza Rooftop', slug: 'elpatiorestaurantbarhabanalaterrazarooft', category: 'restaurant', metros: ['miami'] },
  { name: 'Azteca South Beach', slug: 'aztecasouthbeach', category: 'restaurant', metros: ['miami'] },
  { name: 'll Pastaiolo - Best Italian Restaurant South Beach, Miami Florida', slug: 'llpastaiolo-bestitalianrestaurantsouthbe', category: 'italian', metros: ['miami'] },
  { name: 'Santorini by Georgios', slug: 'santorinibygeorgios', category: 'restaurant', metros: ['miami'] },
  { name: 'Yardbird Table & Bar', slug: 'yardbirdtablebar', category: 'restaurant', metros: ['miami'] },
  { name: 'Meet Dalia', slug: 'meetdalia', category: 'restaurant', metros: ['miami'] },
  { name: 'Café Bastille Miami Beach', slug: 'cafbastillemiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Baia Beach Club Miami', slug: 'baiabeachclubmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'CVI.CHE 105', slug: 'cviche105', category: 'restaurant', metros: ['miami'] },
  { name: 'Pollos & Jarras', slug: 'pollosjarras', category: 'restaurant', metros: ['miami'] },
  { name: 'MAYU by Aromas Del Peru', slug: 'mayubyaromasdelperu', category: 'restaurant', metros: ['miami'] },
  { name: '305 Peruvian Modern Cuisine', slug: '305peruvianmoderncuisine', category: 'restaurant', metros: ['miami'] },
  { name: 'Aromas del Peru', slug: 'aromasdelperu', category: 'restaurant', metros: ['miami'] },
  { name: 'Taipa Peruvian Restaurant- (Coral Gables-57 Ave)', slug: 'taipaperuvianrestaurant-coralgables-57av', category: 'restaurant', metros: ['miami'] },
];

export const NASHVILLE_RESTAURANTS: RestaurantData[] = [
  { name: 'The Finch', slug: 'thefinch', category: 'restaurant', metros: ['nashville'] },
  { name: 'Puckett\'s Restaurant', slug: 'puckettsrestaurant', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Stillery', slug: 'thestillery', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Loveless Cafe', slug: 'thelovelesscafe', category: 'cafe', metros: ['nashville'] },
  { name: 'Lockeland Table', slug: 'lockelandtable', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Hampton Social - Nashville', slug: 'thehamptonsocial-nashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Treehouse Nashville', slug: 'thetreehousenashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'Milk & Honey Gulch', slug: 'milkhoneygulch', category: 'restaurant', metros: ['nashville'] },
  { name: 'Harriet\'s Rooftop', slug: 'harrietsrooftop', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Twelve Thirty Club', slug: 'thetwelvethirtyclub', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Midtown', slug: 'hattiebshotchicken-nashville-midtown', category: 'restaurant', metros: ['nashville'] },
  { name: 'Red\'s Hot Chicken', slug: 'redshotchicken', category: 'restaurant', metros: ['nashville'] },
  { name: 'Champy\'s Nashville', slug: 'champysnashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'Prince\'s Hot Chicken Shack South', slug: 'princeshotchickenshacksouth', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Lower Broadway', slug: 'hattiebshotchicken-nashville-lowerbroadw', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - West', slug: 'hattiebshotchicken-nashville-west', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Melrose', slug: 'hattiebshotchicken-nashville-melrose', category: 'restaurant', metros: ['nashville'] },
  { name: 'Helen\'s Hot Chicken', slug: 'helenshotchicken', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hella Hot Chicken Donelson', slug: 'hellahotchickendonelson', category: 'restaurant', metros: ['nashville'] },
  { name: 'Pepperfire Hot Chicken', slug: 'pepperfirehotchicken', category: 'restaurant', metros: ['nashville'] },
  { name: 'Noko', slug: 'noko', category: 'restaurant', metros: ['nashville'] },
  { name: 'Pelican & Pig', slug: 'pelicanpig', category: 'restaurant', metros: ['nashville'] },
  { name: 'Butcher & Bee', slug: 'butcherbee', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hawkers Asian Street Food', slug: 'hawkersasianstreetfood', category: 'restaurant', metros: ['nashville'] },
  { name: 'Koré', slug: 'kor', category: 'restaurant', metros: ['nashville'] },
  { name: 'Turmeric & Co', slug: 'turmericco', category: 'restaurant', metros: ['nashville'] },
  { name: 'Redheaded Stranger', slug: 'redheadedstranger', category: 'restaurant', metros: ['nashville'] },
  { name: 'Monell\'s', slug: 'monells', category: 'restaurant', metros: ['nashville'] },
  { name: 'Butchertown Hall', slug: 'butchertownhall', category: 'restaurant', metros: ['nashville'] },
  { name: 'Rolf and Daughters', slug: 'rolfanddaughters', category: 'restaurant', metros: ['nashville'] },
  { name: '5th & Taylor', slug: '5thtaylor', category: 'restaurant', metros: ['nashville'] },
  { name: 'Pelato - Nashville', slug: 'pelato-nashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'Germantown Café', slug: 'germantowncaf', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Optimist', slug: 'theoptimist', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Goat Germantown', slug: 'thegoatgermantown', category: 'restaurant', metros: ['nashville'] },
  { name: 'Sedona Taphouse', slug: 'sedonataphouse', category: 'vietnamese', metros: ['nashville'] },
  { name: 'City House', slug: 'cityhouse', category: 'restaurant', metros: ['nashville'] },
  { name: 'V Modern Italian', slug: 'vmodernitalian', category: 'italian', metros: ['nashville'] },
  { name: 'The Iberian Pig', slug: 'theiberianpig', category: 'restaurant', metros: ['nashville'] },
  { name: 'Adele\'s', slug: 'adeles', category: 'restaurant', metros: ['nashville'] },
  { name: 'Luogo', slug: 'luogo', category: 'restaurant', metros: ['nashville'] },
  { name: 'Harper\'s', slug: 'harpers', category: 'restaurant', metros: ['nashville'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['nashville'] },
  { name: 'Kayne Prime', slug: 'kayneprime', category: 'restaurant', metros: ['nashville'] },
];

export const NOLA_RESTAURANTS: RestaurantData[] = [
  { name: 'Brennan\'s', slug: 'brennans', category: 'restaurant', metros: ['nola'] },
  { name: 'Napoleon House', slug: 'napoleonhouse', category: 'restaurant', metros: ['nola'] },
  { name: 'Cochon Restaurant', slug: 'cochonrestaurant', category: 'restaurant', metros: ['nola'] },
  { name: 'Muriel\'s Jackson Square', slug: 'murielsjacksonsquare', category: 'restaurant', metros: ['nola'] },
  { name: 'Commander\'s Palace', slug: 'commanderspalace', category: 'restaurant', metros: ['nola'] },
  { name: 'GW Fins', slug: 'gwfins', category: 'restaurant', metros: ['nola'] },
  { name: 'Cochon Butcher', slug: 'cochonbutcher', category: 'restaurant', metros: ['nola'] },
  { name: 'Olde Nola Cookery', slug: 'oldenolacookery', category: 'restaurant', metros: ['nola'] },
  { name: 'Bourbon House', slug: 'bourbonhouse', category: 'restaurant', metros: ['nola'] },
  { name: 'Luke', slug: 'luke', category: 'restaurant', metros: ['nola'] },
  { name: 'zesty creole', slug: 'zestycreole', category: 'restaurant', metros: ['nola'] },
  { name: 'Mulate\'s | The Original Cajun Restaurant', slug: 'mulatestheoriginalcajunrestaurant', category: 'restaurant', metros: ['nola'] },
  { name: 'Creole House Restaurant & Oyster Bar', slug: 'creolehouserestaurantoysterbar', category: 'seafood', metros: ['nola'] },
  { name: 'Cajun Seafood', slug: 'cajunseafood', category: 'seafood', metros: ['nola'] },
  { name: 'The Original Pierre Maspero\'s', slug: 'theoriginalpierremasperos', category: 'restaurant', metros: ['nola'] },
  { name: 'Mambo’s', slug: 'mambos', category: 'restaurant', metros: ['nola'] },
  { name: 'Hot N Cajun Boil House', slug: 'hotncajunboilhouse', category: 'restaurant', metros: ['nola'] },
  { name: 'Cafe Du Monde', slug: 'cafedumonde', category: 'cafe', metros: ['nola'] },
  { name: 'Restaurant R\'evolution', slug: 'restaurantrevolution', category: 'restaurant', metros: ['nola'] },
  { name: 'Irene\'s', slug: 'irenes', category: 'restaurant', metros: ['nola'] },
  { name: 'Cane and Table', slug: 'caneandtable', category: 'restaurant', metros: ['nola'] },
  { name: 'Elizabeth\'s', slug: 'elizabeths', category: 'restaurant', metros: ['nola'] },
  { name: 'The Joint', slug: 'thejoint', category: 'restaurant', metros: ['nola'] },
  { name: 'The Country Club', slug: 'thecountryclub', category: 'restaurant', metros: ['nola'] },
  { name: 'Sneaky Pickle & Bar Brine', slug: 'sneakypicklebarbrine', category: 'restaurant', metros: ['nola'] },
  { name: 'Bacchanal Fine Wine & Spirits', slug: 'bacchanalfinewinespirits', category: 'restaurant', metros: ['nola'] },
  { name: 'Morrow\'s', slug: 'morrows', category: 'restaurant', metros: ['nola'] },
  { name: 'The Elysian Bar', slug: 'theelysianbar', category: 'restaurant', metros: ['nola'] },
  { name: 'Paladar 511', slug: 'paladar511', category: 'restaurant', metros: ['nola'] },
  { name: 'HONEY\'S', slug: 'honeys', category: 'restaurant', metros: ['nola'] },
  { name: 'JusTini\'s', slug: 'justinis', category: 'restaurant', metros: ['nola'] },
  { name: 'Plates Restaurant & Bar', slug: 'platesrestaurantbar', category: 'restaurant', metros: ['nola'] },
  { name: 'Gris-Gris', slug: 'gris-gris', category: 'restaurant', metros: ['nola'] },
  { name: 'Beggars Banquet', slug: 'beggarsbanquet', category: 'restaurant', metros: ['nola'] },
  { name: 'The Vintage', slug: 'thevintage', category: 'restaurant', metros: ['nola'] },
  { name: 'Atchafalaya', slug: 'atchafalaya', category: 'restaurant', metros: ['nola'] },
  { name: 'Dakar NOLA', slug: 'dakarnola', category: 'restaurant', metros: ['nola'] },
  { name: 'Joey K\'s Restaurant & Bar', slug: 'joeyksrestaurantbar', category: 'restaurant', metros: ['nola'] },
  { name: 'Molly\'s Rise and Shine', slug: 'mollysriseandshine', category: 'restaurant', metros: ['nola'] },
];

export const NYC_RESTAURANTS: RestaurantData[] = [
  { name: 'Monkey Bar', slug: 'monkeybar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sungold Restaurant Brooklyn NY (Arlo Williamsburg)', slug: 'sungoldrestaurantbrooklynnyarlowilliamsb', category: 'restaurant', metros: ['nyc'] },
  { name: 'Recette', slug: 'recette', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hole In The Wall', slug: 'holeinthewall', category: 'restaurant', metros: ['nyc'] },
  { name: 'The River Café', slug: 'therivercaf', category: 'restaurant', metros: ['nyc'] },
  { name: 'Cornbread Brooklyn', slug: 'cornbreadbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fandi Mata', slug: 'fandimata', category: 'restaurant', metros: ['nyc'] },
  { name: 'LILLI RESTAURANT', slug: 'lillirestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sunday In Brooklyn', slug: 'sundayinbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Evelina', slug: 'evelina', category: 'restaurant', metros: ['nyc'] },
  { name: 'Francie', slug: 'francie', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Alcove', slug: 'thealcove', category: 'restaurant', metros: ['nyc'] },
  { name: 'Park Side Restaurant', slug: 'parksiderestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Casa Enrique', slug: 'casaenrique', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mom\'s Kitchen & Bar', slug: 'momskitchenbar', category: 'restaurant', metros: ['nyc'] },
  { name: '(aged.)', slug: 'aged', category: 'restaurant', metros: ['nyc'] },
  { name: 'London Lennie\'s', slug: 'londonlennies', category: 'restaurant', metros: ['nyc'] },
  { name: 'Nan Xiang Soup Dumplings - Flushing', slug: 'nanxiangsoupdumplings-flushing', category: 'restaurant', metros: ['nyc'] },
  { name: 'Florence Prime Diner', slug: 'florenceprimediner', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rainhas Churrascaria', slug: 'rainhaschurrascaria', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fogo de Chão Brazilian Steakhouse', slug: 'fogodechobraziliansteakhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Joe\'s Pizza Broadway', slug: 'joespizzabroadway', category: 'pizza', metros: ['nyc'] },
  { name: 'Nuovo York Pizza', slug: 'nuovoyorkpizza', category: 'pizza', metros: ['nyc'] },
  { name: 'John\'s of Bleecker Street', slug: 'johnsofbleeckerstreet', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rubirosa', slug: 'rubirosa', category: 'restaurant', metros: ['nyc'] },
  { name: 'Lombardi\'s', slug: 'lombardis', category: 'restaurant', metros: ['nyc'] },
  { name: 'NY Pizza Suprema', slug: 'nypizzasuprema', category: 'pizza', metros: ['nyc'] },
  { name: 'OLIO E PIÙ', slug: 'olioepi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Don Antonio', slug: 'donantonio', category: 'restaurant', metros: ['nyc'] },
  { name: 'Kesté Pizza e Vino', slug: 'kestpizzaevino', category: 'pizza', metros: ['nyc'] },
  { name: 'Capizzi', slug: 'capizzi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Jiang Nan NYC', slug: 'jiangnannyc', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shanghai 21', slug: 'shanghai21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Wo Hop', slug: 'wohop', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan', slug: 'thebestsichuan', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都39', slug: 'thebestsichuan39', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都21', slug: 'thebestsichuan21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Chi Restaurant & Bar', slug: 'chirestaurantbar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Uncle Lou 快樂人', slug: 'unclelou', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mountain House', slug: 'mountainhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hutong New York', slug: 'hutongnewyork', category: 'restaurant', metros: ['nyc'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['nyc'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['nyc'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['nyc'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['nyc'] },
  { name: 'Au Cheval', slug: 'aucheval', category: 'restaurant', metros: ['nyc'] },
  { name: '5 Napkin Burger', slug: '5napkinburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger Theater District | Hamburger restaurant Bar', slug: 'blackironburgertheaterdistricthamburgerr', category: 'burgers', metros: ['nyc'] },
  { name: 'Jackson Hole Burgers', slug: 'jacksonholeburgers', category: 'burgers', metros: ['nyc'] },
  { name: 'Bareburger', slug: 'bareburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger', slug: 'blackironburger', category: 'burgers', metros: ['nyc'] },
  { name: 'burger joint', slug: 'burgerjoint', category: 'burgers', metros: ['nyc'] },
  { name: 'Lovely\'s Old Fashioned', slug: 'lovelysoldfashioned', category: 'restaurant', metros: ['nyc'] },
  { name: 'Thai Villa', slug: 'thaivilla', category: 'thai', metros: ['nyc'] },
  { name: 'Mitr Thai Restaurant', slug: 'mitrthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'Elephant Ear', slug: 'elephantear', category: 'restaurant', metros: ['nyc'] },
  { name: 'Soothr', slug: 'soothr', category: 'restaurant', metros: ['nyc'] },
  { name: 'Up Thai', slug: 'upthai', category: 'thai', metros: ['nyc'] },
  { name: 'Hey Thai', slug: 'heythai', category: 'thai', metros: ['nyc'] },
  { name: 'Chalong Southern Thai', slug: 'chalongsouthernthai', category: 'thai', metros: ['nyc'] },
  { name: 'THEP Thai Restaurant', slug: 'thepthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'LumLum', slug: 'lumlum', category: 'restaurant', metros: ['nyc'] },
  { name: 'Pranakhon', slug: 'pranakhon', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Nonnino', slug: 'osterianonnino', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Pecora Bianca SoHo', slug: 'lapecorabiancasoho', category: 'restaurant', metros: ['nyc'] },
  { name: 'Carmine\'s - Time Square', slug: 'carmines-timesquare', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria La Baia', slug: 'osterialabaia', category: 'restaurant', metros: ['nyc'] },
  { name: 'Tony\'s Di Napoli', slug: 'tonysdinapoli', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Barocca', slug: 'osteriabarocca', category: 'restaurant', metros: ['nyc'] },
  { name: 'Scarpetta', slug: 'scarpetta', category: 'restaurant', metros: ['nyc'] },
  { name: 'Ci Siamo', slug: 'cisiamo', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Lanterna di Vittorio', slug: 'lalanternadivittorio', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOLITA', slug: 'lolita', category: 'restaurant', metros: ['nyc'] },
  { name: 'Amor Loco', slug: 'amorloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rosa Mexicano', slug: 'rosamexicano', category: 'mexican', metros: ['nyc'] },
  { name: 'Cosme', slug: 'cosme', category: 'restaurant', metros: ['nyc'] },
  { name: 'Vida Verde - Tequila Bar', slug: 'vidaverde-tequilabar', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Esquina Brasserie', slug: 'laesquinabrasserie', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mamasita Bar & Grill', slug: 'mamasitabargrill', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOS TACOS No.1', slug: 'lostacosno1', category: 'mexican', metros: ['nyc'] },
  { name: 'Toro Loco', slug: 'toroloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Toloache', slug: 'toloache', category: 'restaurant', metros: ['nyc'] },
  { name: 'Kin ramen', slug: 'kinramen', category: 'japanese', metros: ['nyc'] },
  { name: 'Ivan Ramen', slug: 'ivanramen', category: 'japanese', metros: ['nyc'] },
  { name: 'Ichiran', slug: 'ichiran', category: 'restaurant', metros: ['nyc'] },
  { name: 'TONCHIN NEW YORK', slug: 'tonchinnewyork', category: 'restaurant', metros: ['nyc'] },
  { name: 'Loong Ramen', slug: 'loongramen', category: 'japanese', metros: ['nyc'] },
  { name: 'Yasubee Authentic Ramen', slug: 'yasubeeauthenticramen', category: 'japanese', metros: ['nyc'] },
  { name: 'Kyuramen - Union Square', slug: 'kyuramen-unionsquare', category: 'japanese', metros: ['nyc'] },
  { name: 'IPPUDO NY', slug: 'ippudony', category: 'restaurant', metros: ['nyc'] },
  { name: 'RamenYa West Village', slug: 'ramenyawestvillage', category: 'japanese', metros: ['nyc'] },
  { name: 'ICHIRAN Ramen NY Times Square', slug: 'ichiranramennytimessquare', category: 'japanese', metros: ['nyc'] },
  { name: 'Please Don\'t Tell', slug: 'pleasedonttell', category: 'restaurant', metros: ['nyc'] },
  { name: 'Gnocco', slug: 'gnocco', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Smith', slug: 'thesmith', category: 'restaurant', metros: ['nyc'] },
  { name: 'Gemma', slug: 'gemma', category: 'restaurant', metros: ['nyc'] },
  { name: 'Thursday Kitchen', slug: 'thursdaykitchen', category: 'restaurant', metros: ['nyc'] },
  { name: 'Somtum Der', slug: 'somtumder', category: 'restaurant', metros: ['nyc'] },
  { name: 'Cafe Mogador', slug: 'cafemogador', category: 'cafe', metros: ['nyc'] },
  { name: 'San Marzano', slug: 'sanmarzano', category: 'restaurant', metros: ['nyc'] },
  { name: 'Via Della Pace', slug: 'viadellapace', category: 'restaurant', metros: ['nyc'] },
  { name: 'Aurora Brooklyn', slug: 'aurorabrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Le Crocodile', slug: 'lecrocodile', category: 'restaurant', metros: ['nyc'] },
  { name: 'Isla & Co. - Williamsburg', slug: 'islaco-williamsburg', category: 'restaurant', metros: ['nyc'] },
  { name: 'Antidote', slug: 'antidote', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Four Horsemen', slug: 'thefourhorsemen', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sanfords', slug: 'sanfords', category: 'restaurant', metros: ['nyc'] },
  { name: 'Taverna Kyclades Astoria', slug: 'tavernakycladesastoria', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Bonnie', slug: 'thebonnie', category: 'restaurant', metros: ['nyc'] },
  { name: 'Anassa Taverna Astoria', slug: 'anassatavernaastoria', category: 'restaurant', metros: ['nyc'] },
  { name: 'Bahari Estiatorio', slug: 'bahariestiatorio', category: 'restaurant', metros: ['nyc'] },
  { name: 'Kam Rai Thai', slug: 'kamraithai', category: 'thai', metros: ['nyc'] },
  { name: 'Bel Aire Diner', slug: 'belairediner', category: 'restaurant', metros: ['nyc'] },
  { name: 'Agnanti', slug: 'agnanti', category: 'restaurant', metros: ['nyc'] },
  { name: 'VITE vinosteria', slug: 'vitevinosteria', category: 'restaurant', metros: ['nyc'] },
  { name: 'Bungalow', slug: 'bungalow', category: 'restaurant', metros: ['nyc'] },
  { name: 'Cloves Indian Cuisine', slug: 'clovesindiancuisine', category: 'indian', metros: ['nyc'] },
  { name: 'Indian Accent', slug: 'indianaccent', category: 'indian', metros: ['nyc'] },
  { name: 'Patiala Indian Grill & Bar', slug: 'patialaindiangrillbar', category: 'indian', metros: ['nyc'] },
  { name: 'Junoon', slug: 'junoon', category: 'restaurant', metros: ['nyc'] },
  { name: 'Spice Symphony Times Square', slug: 'spicesymphonytimessquare', category: 'vietnamese', metros: ['nyc'] },
  { name: 'Vatan', slug: 'vatan', category: 'restaurant', metros: ['nyc'] },
  { name: 'Red Onion Indian Lunch Brunch Dinner', slug: 'redonionindianlunchbrunchdinner', category: 'indian', metros: ['nyc'] },
  { name: 'Dhamaka', slug: 'dhamaka', category: 'restaurant', metros: ['nyc'] },
  { name: 'GupShup', slug: 'gupshup', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sylvia\'s Restaurant', slug: 'sylviasrestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Red Rooster Harlem', slug: 'redroosterharlem', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Edge Harlem', slug: 'theedgeharlem', category: 'restaurant', metros: ['nyc'] },
  { name: 'Angel of Harlem', slug: 'angelofharlem', category: 'restaurant', metros: ['nyc'] },
  { name: 'Harlem Public', slug: 'harlempublic', category: 'restaurant', metros: ['nyc'] },
  { name: 'Amy Ruth\'s', slug: 'amyruths', category: 'restaurant', metros: ['nyc'] },
  { name: 'Lido Harlem Restaurant', slug: 'lidoharlemrestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Maison Harlem', slug: 'maisonharlem', category: 'restaurant', metros: ['nyc'] },
  { name: 'Corner Social', slug: 'cornersocial', category: 'restaurant', metros: ['nyc'] },
  { name: 'Jacob Soul Food Restaurant', slug: 'jacobsoulfoodrestaurant', category: 'southern', metros: ['nyc'] },
  { name: 'La Dong', slug: 'ladong', category: 'restaurant', metros: ['nyc'] },
  { name: 'OBAO', slug: 'obao', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hanoi House', slug: 'hanoihouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Madame Vo', slug: 'madamevo', category: 'restaurant', metros: ['nyc'] },
  { name: 'Ly Ly Vietnam Cookhouse', slug: 'lylyvietnamcookhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Nom Nam', slug: 'nomnam', category: 'restaurant', metros: ['nyc'] },
  { name: 'Saigon Shack', slug: 'saigonshack', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sao Mai', slug: 'saomai', category: 'restaurant', metros: ['nyc'] },
  { name: 'Nha Trang One', slug: 'nhatrangone', category: 'restaurant', metros: ['nyc'] },
  { name: 'OBAO Midtown', slug: 'obaomidtown', category: 'restaurant', metros: ['nyc'] },
  { name: 'Lillie\'s Victorian Establishment', slug: 'lilliesvictorianestablishment', category: 'restaurant', metros: ['nyc'] },
  { name: 'Isla & Co. Lower East Side', slug: 'islacolowereastside', category: 'restaurant', metros: ['nyc'] },
  { name: 'Essex', slug: 'essex', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sixty Three Clinton', slug: 'sixtythreeclinton', category: 'restaurant', metros: ['nyc'] },
  { name: 'Beauty & Essex', slug: 'beautyessex', category: 'restaurant', metros: ['nyc'] },
  { name: 'Freemans', slug: 'freemans', category: 'restaurant', metros: ['nyc'] },
  { name: 'LECIEL', slug: 'leciel', category: 'restaurant', metros: ['nyc'] },
  { name: 'Dirt Candy', slug: 'dirtcandy', category: 'restaurant', metros: ['nyc'] },
  { name: 'Bufón', slug: 'bufn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Dallas BBQ', slug: 'dallasbbq', category: 'bbq', metros: ['nyc'] },
  { name: 'Virgil\'s Real BBQ - NYC', slug: 'virgilsrealbbq-nyc', category: 'bbq', metros: ['nyc'] },
  { name: 'Chubby Cattle BBQ | New York', slug: 'chubbycattlebbqnewyork', category: 'bbq', metros: ['nyc'] },
  { name: 'Hill Country Barbecue Market', slug: 'hillcountrybarbecuemarket', category: 'bbq', metros: ['nyc'] },
  { name: 'Hometown Bar-B-Que', slug: 'hometownbar-b-que', category: 'restaurant', metros: ['nyc'] },
  { name: 'miss KOREA BBQ', slug: 'misskoreabbq', category: 'bbq', metros: ['nyc'] },
  { name: 'Pig Beach BBQ Queens', slug: 'pigbeachbbqqueens', category: 'bbq', metros: ['nyc'] },
  { name: 'Mighty Quinn\'s Barbeque', slug: 'mightyquinnsbarbeque', category: 'restaurant', metros: ['nyc'] },
  { name: 'Dallas BBQ Chelsea', slug: 'dallasbbqchelsea', category: 'bbq', metros: ['nyc'] },
  { name: 'Sisters', slug: 'sisters', category: 'restaurant', metros: ['nyc'] },
  { name: 'Five Leaves', slug: 'fiveleaves', category: 'restaurant', metros: ['nyc'] },
  { name: 'French Louie', slug: 'frenchlouie', category: 'french', metros: ['nyc'] },
  { name: 'Shane\'s Brooklyn', slug: 'shanesbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Premier Deli', slug: 'premierdeli', category: 'deli', metros: ['nyc'] },
  { name: 'Pastrami Queen', slug: 'pastramiqueen', category: 'restaurant', metros: ['nyc'] },
  { name: 'All\'Antico Vinaio', slug: 'allanticovinaio', category: 'restaurant', metros: ['nyc'] },
  { name: 'Panineria NYC', slug: 'paninerianyc', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sal, Kris & Charlie\'s Deli', slug: 'salkrischarliesdeli', category: 'deli', metros: ['nyc'] },
  { name: 'Frankel\'s Delicatessen & Appetizing', slug: 'frankelsdelicatessenappetizing', category: 'deli', metros: ['nyc'] },
  { name: 'David\'s Brisket House', slug: 'davidsbriskethouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Defonte\'s Sandwich Shop', slug: 'defontessandwichshop', category: 'deli', metros: ['nyc'] },
  { name: 'Eisenberg\'s Sandwich Shop', slug: 'eisenbergssandwichshop', category: 'deli', metros: ['nyc'] },
  { name: 'Eataly', slug: 'eataly', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shaw-nae’s House', slug: 'shaw-naeshouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Taste Of Heaven', slug: 'tasteofheaven', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Donna Re\'s', slug: 'ladonnares', category: 'restaurant', metros: ['nyc'] },
  { name: 'SoulTye', slug: 'soultye', category: 'southern', metros: ['nyc'] },
  { name: 'Blossom\'s Soul Food Fusion', slug: 'blossomssoulfoodfusion', category: 'southern', metros: ['nyc'] },
  { name: 'Melba\'s Restaurant', slug: 'melbasrestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Dead Poet', slug: 'thedeadpoet', category: 'restaurant', metros: ['nyc'] },
  { name: 'BARBOUNIA', slug: 'barbounia', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shuka', slug: 'shuka', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shukette', slug: 'shukette', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mama Mezze', slug: 'mamamezze', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sea Salt NYC', slug: 'seasaltnyc', category: 'restaurant', metros: ['nyc'] },
  { name: 'ilili NoMad', slug: 'ililinomad', category: 'restaurant', metros: ['nyc'] },
  { name: 'Zou Zou’s', slug: 'zouzous', category: 'restaurant', metros: ['nyc'] },
  { name: 'Zaytinya', slug: 'zaytinya', category: 'restaurant', metros: ['nyc'] },
  { name: 'ZOI MEDITERRANEAN NOMAD', slug: 'zoimediterraneannomad', category: 'mediterranean', metros: ['nyc'] },
  { name: 'White Olive', slug: 'whiteolive', category: 'restaurant', metros: ['nyc'] },
];

export const PHILLY_RESTAURANTS: RestaurantData[] = [
  { name: 'The Dandelion', slug: 'thedandelion', category: 'deli', metros: ['philly'] },
  { name: 'Talula\'s Garden', slug: 'talulasgarden', category: 'restaurant', metros: ['philly'] },
  { name: 'The Love.', slug: 'thelove', category: 'restaurant', metros: ['philly'] },
  { name: 'Harper\'s Garden', slug: 'harpersgarden', category: 'restaurant', metros: ['philly'] },
  { name: 'Wilder', slug: 'wilder', category: 'restaurant', metros: ['philly'] },
  { name: 'Jean-Georges Philadelphia', slug: 'jean-georgesphiladelphia', category: 'restaurant', metros: ['philly'] },
  { name: 'Butcher and Singer', slug: 'butcherandsinger', category: 'restaurant', metros: ['philly'] },
  { name: 'Harp & Crown', slug: 'harpcrown', category: 'restaurant', metros: ['philly'] },
  { name: 'Little Nonna\'s', slug: 'littlenonnas', category: 'restaurant', metros: ['philly'] },
  { name: 'Skyhigh', slug: 'skyhigh', category: 'restaurant', metros: ['philly'] },
  { name: 'Osteria Ama Philly', slug: 'osteriaamaphilly', category: 'restaurant', metros: ['philly'] },
  { name: 'Wm. Mulherin’s Sons', slug: 'wmmulherinssons', category: 'restaurant', metros: ['philly'] },
  { name: 'Suraya Restaurant', slug: 'surayarestaurant', category: 'restaurant', metros: ['philly'] },
  { name: 'Fabrika', slug: 'fabrika', category: 'restaurant', metros: ['philly'] },
  { name: 'LMNO', slug: 'lmno', category: 'restaurant', metros: ['philly'] },
  { name: 'Elwood', slug: 'elwood', category: 'restaurant', metros: ['philly'] },
  { name: 'Front Street Cafe', slug: 'frontstreetcafe', category: 'cafe', metros: ['philly'] },
  { name: 'Forest & Main Fishtown', slug: 'forestmainfishtown', category: 'seafood', metros: ['philly'] },
  { name: 'Fette Sau', slug: 'fettesau', category: 'restaurant', metros: ['philly'] },
  { name: 'Middle Child Clubhouse', slug: 'middlechildclubhouse', category: 'restaurant', metros: ['philly'] },
  { name: 'Two Robbers Fishtown', slug: 'tworobbersfishtown', category: 'seafood', metros: ['philly'] },
  { name: 'Ember & Ash', slug: 'emberash', category: 'restaurant', metros: ['philly'] },
  { name: 'Le Virtù', slug: 'levirt', category: 'restaurant', metros: ['philly'] },
  { name: 'Indo Spice Restaurant', slug: 'indospicerestaurant', category: 'restaurant', metros: ['philly'] },
  { name: 'Alice', slug: 'alice', category: 'restaurant', metros: ['philly'] },
  { name: 'Fiorella Pasta', slug: 'fiorellapasta', category: 'italian', metros: ['philly'] },
  { name: 'South Philly Barbacoa', slug: 'southphillybarbacoa', category: 'restaurant', metros: ['philly'] },
  { name: 'Rex at the Royal', slug: 'rexattheroyal', category: 'restaurant', metros: ['philly'] },
  { name: 'Bucatini Caffè', slug: 'bucatinicaff', category: 'restaurant', metros: ['philly'] },
  { name: 'Mish Mish', slug: 'mishmish', category: 'restaurant', metros: ['philly'] },
  { name: 'Bourbon & Branch', slug: 'bourbonbranch', category: 'restaurant', metros: ['philly'] },
  { name: 'SET NoLibs', slug: 'setnolibs', category: 'restaurant', metros: ['philly'] },
  { name: 'Silk City', slug: 'silkcity', category: 'restaurant', metros: ['philly'] },
  { name: 'Cafe La Maude', slug: 'cafelamaude', category: 'cafe', metros: ['philly'] },
  { name: 'Urban Village Brewing Company', slug: 'urbanvillagebrewingcompany', category: 'wings', metros: ['philly'] },
  { name: 'North Third', slug: 'norththird', category: 'restaurant', metros: ['philly'] },
  { name: 'Standard Tap', slug: 'standardtap', category: 'restaurant', metros: ['philly'] },
  { name: 'AMINA', slug: 'amina', category: 'restaurant', metros: ['philly'] },
  { name: 'Buddakan', slug: 'buddakan', category: 'restaurant', metros: ['philly'] },
  { name: 'Sampan', slug: 'sampan', category: 'restaurant', metros: ['philly'] },
  { name: 'Grandma\'s Philly', slug: 'grandmasphilly', category: 'restaurant', metros: ['philly'] },
  { name: 'Double Knot', slug: 'doubleknot', category: 'restaurant', metros: ['philly'] },
  { name: 'Morimoto', slug: 'morimoto', category: 'restaurant', metros: ['philly'] },
  { name: 'Ji Bei Chuan Philly', slug: 'jibeichuanphilly', category: 'restaurant', metros: ['philly'] },
  { name: 'Mari Mari', slug: 'marimari', category: 'restaurant', metros: ['philly'] },
  { name: 'Nom Wah Philadelphia', slug: 'nomwahphiladelphia', category: 'restaurant', metros: ['philly'] },
  { name: 'Mawn', slug: 'mawn', category: 'restaurant', metros: ['philly'] },
  { name: 'EMei 峨嵋', slug: 'emei', category: 'restaurant', metros: ['philly'] },
  { name: 'Louie Louie', slug: 'louielouie', category: 'restaurant', metros: ['philly'] },
  { name: 'White Dog Cafe University City', slug: 'whitedogcafeuniversitycity', category: 'cafe', metros: ['philly'] },
  { name: 'Walnut Street Cafe', slug: 'walnutstreetcafe', category: 'cafe', metros: ['philly'] },
  { name: 'LaScala\'s FIRE - University City', slug: 'lascalasfire-universitycity', category: 'restaurant', metros: ['philly'] },
  { name: 'Sabrina\'s Cafe', slug: 'sabrinascafe', category: 'cafe', metros: ['philly'] },
  { name: 'CO-OP Restaurant & Bar', slug: 'co-oprestaurantbar', category: 'restaurant', metros: ['philly'] },
  { name: 'New Deck Tavern', slug: 'newdecktavern', category: 'restaurant', metros: ['philly'] },
];

export const SEATTLE_RESTAURANTS: RestaurantData[] = [
  { name: 'Can Can Seattle: A Culinary Cabaret', slug: 'cancanseattleaculinarycabaret', category: 'restaurant', metros: ['seattle'] },
  { name: 'Kedai Makan Capitol Hill', slug: 'kedaimakancapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'Spinasse', slug: 'spinasse', category: 'restaurant', metros: ['seattle'] },
  { name: 'The Pink Door', slug: 'thepinkdoor', category: 'restaurant', metros: ['seattle'] },
  { name: 'Momiji Capitol Hill', slug: 'momijicapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'Nue', slug: 'nue', category: 'restaurant', metros: ['seattle'] },
  { name: 'Terra Plata', slug: 'terraplata', category: 'restaurant', metros: ['seattle'] },
  { name: 'Taurus Ox', slug: 'taurusox', category: 'restaurant', metros: ['seattle'] },
  { name: 'Ba Bar Capitol Hill', slug: 'babarcapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'MariPili Tapas Bar', slug: 'maripilitapasbar', category: 'restaurant', metros: ['seattle'] },
  { name: 'Taneda', slug: 'taneda', category: 'restaurant', metros: ['seattle'] },
  { name: 'Fuego Restaurant Lounge Ballard', slug: 'fuegorestaurantloungeballard', category: 'restaurant', metros: ['seattle'] },
  { name: 'The Walrus and the Carpenter', slug: 'thewalrusandthecarpenter', category: 'restaurant', metros: ['seattle'] },
  { name: 'Brimmer & Heeltap', slug: 'brimmerheeltap', category: 'restaurant', metros: ['seattle'] },
  { name: 'Asadero Ballard', slug: 'asaderoballard', category: 'restaurant', metros: ['seattle'] },
  { name: 'Ray\'s Boathouse', slug: 'raysboathouse', category: 'restaurant', metros: ['seattle'] },
  { name: 'Sabine Café & Bar', slug: 'sabinecafbar', category: 'restaurant', metros: ['seattle'] },
  { name: 'Secret Congee', slug: 'secretcongee', category: 'restaurant', metros: ['seattle'] },
  { name: 'Ray\'s Cafe', slug: 'rayscafe', category: 'cafe', metros: ['seattle'] },
  { name: 'Stoneburner', slug: 'stoneburner', category: 'restaurant', metros: ['seattle'] },
  { name: 'San Fermo', slug: 'sanfermo', category: 'restaurant', metros: ['seattle'] },
  { name: 'Bongos', slug: 'bongos', category: 'restaurant', metros: ['seattle'] },
  { name: 'Wild Ginger Downtown Seattle', slug: 'wildgingerdowntownseattle', category: 'restaurant', metros: ['seattle'] },
  { name: 'Din Tai Fung 鼎泰豐', slug: 'dintaifung', category: 'restaurant', metros: ['seattle'] },
  { name: 'E-Jae Pak Mor', slug: 'e-jaepakmor', category: 'restaurant', metros: ['seattle'] },
  { name: 'Tai Tung Restaurant', slug: 'taitungrestaurant', category: 'restaurant', metros: ['seattle'] },
  { name: 'Noi Thai Cuisine', slug: 'noithaicuisine', category: 'thai', metros: ['seattle'] },
  { name: '8 Ping Yang', slug: '8pingyang', category: 'restaurant', metros: ['seattle'] },
  { name: 'P. F. Chang\'s - SEA', slug: 'pfchangs-sea', category: 'restaurant', metros: ['seattle'] },
  { name: 'Monsoon Seattle', slug: 'monsoonseattle', category: 'restaurant', metros: ['seattle'] },
  { name: 'Seastar Restaurant & Raw Bar', slug: 'seastarrestaurantrawbar', category: 'restaurant', metros: ['seattle'] },
  { name: 'The Pumphouse Bar & Grill', slug: 'thepumphousebargrill', category: 'vietnamese', metros: ['seattle'] },
  { name: 'Wild Ginger Bellevue', slug: 'wildgingerbellevue', category: 'restaurant', metros: ['seattle'] },
];

export const SF_RESTAURANTS: RestaurantData[] = [
  { name: 'Nopa', slug: 'nopa', category: 'restaurant', metros: ['sf'] },
  { name: 'The View Lounge', slug: 'theviewlounge', category: 'restaurant', metros: ['sf'] },
  { name: 'Zeitgeist', slug: 'zeitgeist', category: 'restaurant', metros: ['sf'] },
  { name: 'Absinthe Brasserie & Bar', slug: 'absinthebrasseriebar', category: 'restaurant', metros: ['sf'] },
  { name: 'Lazy Bear', slug: 'lazybear', category: 'restaurant', metros: ['sf'] },
  { name: 'Bottega', slug: 'bottega', category: 'restaurant', metros: ['sf'] },
  { name: 'The Morris', slug: 'themorris', category: 'restaurant', metros: ['sf'] },
  { name: 'The Rabbit Hole', slug: 'therabbithole', category: 'restaurant', metros: ['sf'] },
  { name: 'La Taqueria', slug: 'lataqueria', category: 'restaurant', metros: ['sf'] },
  { name: 'Beretta Valencia', slug: 'berettavalencia', category: 'restaurant', metros: ['sf'] },
  { name: 'Rintaro', slug: 'rintaro', category: 'restaurant', metros: ['sf'] },
  { name: 'Foreign Cinema', slug: 'foreigncinema', category: 'restaurant', metros: ['sf'] },
  { name: 'Sangria & Salt', slug: 'sangriasalt', category: 'restaurant', metros: ['sf'] },
  { name: 'Lolinda', slug: 'lolinda', category: 'restaurant', metros: ['sf'] },
  { name: 'Sforno Pizzeria Napoletana', slug: 'sfornopizzerianapoletana', category: 'restaurant', metros: ['sf'] },
  { name: 'a Mano', slug: 'amano', category: 'restaurant', metros: ['sf'] },
  { name: 'Rich Table', slug: 'richtable', category: 'restaurant', metros: ['sf'] },
  { name: 'Hazie\'s', slug: 'hazies', category: 'restaurant', metros: ['sf'] },
  { name: 'Chez Maman West', slug: 'chezmamanwest', category: 'restaurant', metros: ['sf'] },
  { name: 'Suppenküche', slug: 'suppenkche', category: 'restaurant', metros: ['sf'] },
  { name: 'Doppio Zero San Francisco', slug: 'doppiozerosanfrancisco', category: 'restaurant', metros: ['sf'] },
  { name: 'Papito Hayes', slug: 'papitohayes', category: 'restaurant', metros: ['sf'] },
  { name: 'The Gambit', slug: 'thegambit', category: 'restaurant', metros: ['sf'] },
  { name: 'North Beach Restaurant', slug: 'northbeachrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'Tony\'s Pizza Napoletana', slug: 'tonyspizzanapoletana', category: 'pizza', metros: ['sf'] },
  { name: 'Sotto Mare', slug: 'sottomare', category: 'restaurant', metros: ['sf'] },
  { name: 'Original Joe\'s', slug: 'originaljoes', category: 'restaurant', metros: ['sf'] },
  { name: 'The Italian Homemade Company', slug: 'theitalianhomemadecompany', category: 'italian', metros: ['sf'] },
  { name: 'The Stinking Rose', slug: 'thestinkingrose', category: 'restaurant', metros: ['sf'] },
  { name: 'Fog Harbor Fish House', slug: 'fogharborfishhouse', category: 'seafood', metros: ['sf'] },
  { name: 'Golden Boy Pizza', slug: 'goldenboypizza', category: 'pizza', metros: ['sf'] },
  { name: 'Beach Chalet Brewery and Restaurant', slug: 'beachchaletbreweryandrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'Scoma\'s Restaurant', slug: 'scomasrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'Dragon Beaux', slug: 'dragonbeaux', category: 'restaurant', metros: ['sf'] },
  { name: 'HK Lounge Bistro', slug: 'hkloungebistro', category: 'french', metros: ['sf'] },
  { name: 'Good Luck Dim Sum', slug: 'goodluckdimsum', category: 'chinese', metros: ['sf'] },
  { name: 'Dumpling Time Design District', slug: 'dumplingtimedesigndistrict', category: 'chinese', metros: ['sf'] },
  { name: 'Good Mong Kok Bakery', slug: 'goodmongkokbakery', category: 'cafe', metros: ['sf'] },
  { name: 'City View Restaurant', slug: 'cityviewrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'DIM SUM BEST Of TASTE', slug: 'dimsumbestoftaste', category: 'chinese', metros: ['sf'] },
  { name: 'Yank Sing (Stevenson St.)', slug: 'yanksingstevensonst', category: 'restaurant', metros: ['sf'] },
  { name: 'Bao Bao Dumpling', slug: 'baobaodumpling', category: 'chinese', metros: ['sf'] },
  { name: 'Palette Tea House', slug: 'paletteteahouse', category: 'restaurant', metros: ['sf'] },
  { name: 'The Fat Lady Bar & Restaurant', slug: 'thefatladybarrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'Wood Tavern', slug: 'woodtavern', category: 'restaurant', metros: ['sf'] },
  { name: 'Almond and Oak', slug: 'almondandoak', category: 'restaurant', metros: ['sf'] },
  { name: 'Drake\'s Dealership', slug: 'drakesdealership', category: 'restaurant', metros: ['sf'] },
  { name: 'Scott\'s Seafood Grill & Bar', slug: 'scottsseafoodgrillbar', category: 'seafood', metros: ['sf'] },
  { name: 'The Lake Chalet Seafood Bar & Grill', slug: 'thelakechaletseafoodbargrill', category: 'seafood', metros: ['sf'] },
  { name: 'Pomet', slug: 'pomet', category: 'restaurant', metros: ['sf'] },
  { name: 'NIDO\'s BackYard', slug: 'nidosbackyard', category: 'restaurant', metros: ['sf'] },
  { name: 'The Cook and Her Farmer', slug: 'thecookandherfarmer', category: 'restaurant', metros: ['sf'] },
  { name: 'Quinn\'s Lighthouse', slug: 'quinnslighthouse', category: 'restaurant', metros: ['sf'] },
  { name: 'Fable', slug: 'fable', category: 'restaurant', metros: ['sf'] },
  { name: 'Anchor Oyster Bar', slug: 'anchoroysterbar', category: 'seafood', metros: ['sf'] },
  { name: 'Orphan Andy\'s Restaurant', slug: 'orphanandysrestaurant', category: 'restaurant', metros: ['sf'] },
  { name: 'L\'Ardoise Bistro', slug: 'lardoisebistro', category: 'french', metros: ['sf'] },
  { name: 'Poesia', slug: 'poesia', category: 'restaurant', metros: ['sf'] },
  { name: 'Starbelly', slug: 'starbelly', category: 'restaurant', metros: ['sf'] },
  { name: 'Frances', slug: 'frances', category: 'restaurant', metros: ['sf'] },
  { name: 'Flora King Steakhouse', slug: 'florakingsteakhouse', category: 'steakhouse', metros: ['sf'] },
  { name: 'Potto', slug: 'potto', category: 'restaurant', metros: ['sf'] },
  { name: 'Blind Butcher', slug: 'blindbutcher', category: 'restaurant', metros: ['sf'] },
];

