
// ─── New City Restaurants (Google Places discovery, Feb 12) ────

export const ATLANTA_RESTAURANTS: RestaurantData[] = [
  { name: 'TWO urban licks', slug: 'twourbanlicks', category: 'restaurant', metros: ['atlanta'] },
  { name: '9 Mile Station', slug: '9milestation', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Mary Mac\'s Tea Room', slug: 'marymacstearoom', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Sugar Factory American Brasserie - Atlanta', slug: 'sugarfactoryamericanbrasserie-atlanta', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Hungry AF Downtown', slug: 'hungryafdowntown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Marcel', slug: 'marcel', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ray\'s In the City', slug: 'raysinthecity', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ladybird Grove & Mess Hall', slug: 'ladybirdgrovemesshall', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Sun Dial Restaurant, Bar & View', slug: 'thesundialrestaurantbarview', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Canoe', slug: 'canoe', category: 'restaurant', metros: ['atlanta'] },
  { name: 'South City Kitchen Midtown', slug: 'southcitykitchenmidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'El Viñedo Local', slug: 'elviedolocal', category: 'restaurant', metros: ['atlanta'] },
  { name: 'The Consulate Restaurant', slug: 'theconsulaterestaurant', category: 'restaurant', metros: ['atlanta'] },
  { name: '5Church Midtown', slug: '5churchmidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Crescent City Kitchen', slug: 'crescentcitykitchen', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Boqueria Colony Sqaure', slug: 'boqueriacolonysqaure', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Wagyu House Atlanta', slug: 'wagyuhouseatlanta', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Ecco Midtown', slug: 'eccomidtown', category: 'restaurant', metros: ['atlanta'] },
  { name: 'Yebo Beach Haus', slug: 'yebobeachhaus', category: 'restaurant', metros: ['atlanta'] },
];

export const BOSTON_RESTAURANTS: RestaurantData[] = [
  { name: 'The Salty Pig', slug: 'thesaltypig', category: 'restaurant', metros: ['boston'] },
  { name: 'Saltie Girl', slug: 'saltiegirl', category: 'restaurant', metros: ['boston'] },
  { name: 'Beehive Restaurant', slug: 'beehiverestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Mamma Maria', slug: 'mammamaria', category: 'restaurant', metros: ['boston'] },
  { name: 'Grill 23 & Bar', slug: 'grill23bar', category: 'restaurant', metros: ['boston'] },
  { name: 'Coquette', slug: 'coquette', category: 'restaurant', metros: ['boston'] },
  { name: 'Atlantic Fish Company', slug: 'atlanticfishcompany', category: 'seafood', metros: ['boston'] },
  { name: 'Boston Sail Loft', slug: 'bostonsailloft', category: 'restaurant', metros: ['boston'] },
  { name: 'Legal Sea Foods - Harborside', slug: 'legalseafoods-harborside', category: 'restaurant', metros: ['boston'] },
  { name: 'Ostra', slug: 'ostra', category: 'restaurant', metros: ['boston'] },
  { name: 'James Hook & Co', slug: 'jameshookco', category: 'restaurant', metros: ['boston'] },
  { name: 'The Oceanaire Seafood Room', slug: 'theoceanaireseafoodroom', category: 'seafood', metros: ['boston'] },
  { name: 'Chart House', slug: 'charthouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Union Oyster House', slug: 'unionoysterhouse', category: 'seafood', metros: ['boston'] },
  { name: 'STK Steakhouse', slug: 'stksteakhouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Wusong Tiki Bar', slug: 'wusongtikibar', category: 'restaurant', metros: ['boston'] },
  { name: 'Highland Kitchen', slug: 'highlandkitchen', category: 'restaurant', metros: ['boston'] },
  { name: 'Carmelina\'s', slug: 'carmelinas', category: 'restaurant', metros: ['boston'] },
  { name: 'La Famiglia Giorgio\'s Restaurant', slug: 'lafamigliagiorgiosrestaurant', category: 'restaurant', metros: ['boston'] },
  { name: 'Giacomo\'s Boston North End', slug: 'giacomosbostonnorthend', category: 'restaurant', metros: ['boston'] },
  { name: 'Prezza', slug: 'prezza', category: 'restaurant', metros: ['boston'] },
  { name: 'Limoncello', slug: 'limoncello', category: 'restaurant', metros: ['boston'] },
  { name: 'Little Sage', slug: 'littlesage', category: 'restaurant', metros: ['boston'] },
  { name: 'Antico Forno', slug: 'anticoforno', category: 'restaurant', metros: ['boston'] },
  { name: 'Bricco', slug: 'bricco', category: 'restaurant', metros: ['boston'] },
  { name: 'Cantina Italiana', slug: 'cantinaitaliana', category: 'italian', metros: ['boston'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['boston'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['boston'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['boston'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['boston'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['boston'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['boston'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['boston'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['boston'] },
];

export const CHICAGO_RESTAURANTS: RestaurantData[] = [
  { name: 'Girl & The Goat', slug: 'girlthegoat', category: 'restaurant', metros: ['chicago'] },
  { name: 'River Roast', slug: 'riverroast', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Dearborn', slug: 'thedearborn', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Purple Pig Restaurant', slug: 'thepurplepigrestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'Elephant & Castle', slug: 'elephantcastle', category: 'restaurant', metros: ['chicago'] },
  { name: 'Alla Vita', slug: 'allavita', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carnivale Chicago', slug: 'carnivalechicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Beatnik On The River', slug: 'beatnikontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Quartino Ristorante', slug: 'quartinoristorante', category: 'restaurant', metros: ['chicago'] },
  { name: 'Eataly', slug: 'eataly', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pizzeria Portofino', slug: 'pizzeriaportofino', category: 'restaurant', metros: ['chicago'] },
  { name: 'Giordano\'s', slug: 'giordanos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Gino\'s East', slug: 'ginoseast', category: 'restaurant', metros: ['chicago'] },
  { name: 'Zarella Pizzeria & Taverna', slug: 'zarellapizzeriataverna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Pequod\'s Pizza', slug: 'pequodspizza', category: 'pizza', metros: ['chicago'] },
  { name: 'Spacca Napoli Pizzeria', slug: 'spaccanapolipizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Lou Malnati\'s Pizzeria', slug: 'loumalnatispizzeria', category: 'restaurant', metros: ['chicago'] },
  { name: 'Robert\'s Pizza and Dough Company', slug: 'robertspizzaanddoughcompany', category: 'pizza', metros: ['chicago'] },
  { name: 'Labriola Ristorante - Chicago', slug: 'labriolaristorante-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'The Perch Kitchen and Tap', slug: 'theperchkitchenandtap', category: 'restaurant', metros: ['chicago'] },
  { name: 'Big Star Wicker Park', slug: 'bigstarwickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Paradise Park | Pizza & Patio', slug: 'paradiseparkpizzapatio', category: 'pizza', metros: ['chicago'] },
  { name: 'Elia Chicago', slug: 'eliachicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ina Mae', slug: 'inamae', category: 'restaurant', metros: ['chicago'] },
  { name: 'Amaru', slug: 'amaru', category: 'restaurant', metros: ['chicago'] },
  { name: 'Handlebar', slug: 'handlebar', category: 'restaurant', metros: ['chicago'] },
  { name: 'Piece Pizzeria and Brewery', slug: 'piecepizzeriaandbrewery', category: 'restaurant', metros: ['chicago'] },
  { name: 'Cafe Robey', slug: 'caferobey', category: 'cafe', metros: ['chicago'] },
  { name: 'Bangers & Lace Wicker Park', slug: 'bangerslacewickerpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Summer House Santa Monica', slug: 'summerhousesantamonica', category: 'restaurant', metros: ['chicago'] },
  { name: 'Boka', slug: 'boka', category: 'restaurant', metros: ['chicago'] },
  { name: 'Blue Door Farm Stand', slug: 'bluedoorfarmstand', category: 'restaurant', metros: ['chicago'] },
  { name: 'North Pond', slug: 'northpond', category: 'restaurant', metros: ['chicago'] },
  { name: 'Mon Ami Gabi', slug: 'monamigabi', category: 'restaurant', metros: ['chicago'] },
  { name: 'GEMINI', slug: 'gemini', category: 'restaurant', metros: ['chicago'] },
  { name: 'Armitage Alehouse', slug: 'armitagealehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'DeNucci\'s Lincoln Park', slug: 'denuccislincolnpark', category: 'restaurant', metros: ['chicago'] },
  { name: 'Willow Room', slug: 'willowroom', category: 'restaurant', metros: ['chicago'] },
  { name: 'Aba', slug: 'aba', category: 'restaurant', metros: ['chicago'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['chicago'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['chicago'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['chicago'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['chicago'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['chicago'] },
  { name: 'Café No Sé', slug: 'cafnos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Costera Cocina Tulum - Chicago', slug: 'costeracocinatulum-chicago', category: 'restaurant', metros: ['chicago'] },
  { name: 'Ayayay - Mexican Eatery', slug: 'ayayay-mexicaneatery', category: 'mexican', metros: ['chicago'] },
  { name: 'Mercadito', slug: 'mercadito', category: 'restaurant', metros: ['chicago'] },
  { name: 'Casa Tulum', slug: 'casatulum', category: 'restaurant', metros: ['chicago'] },
  { name: 'Tzuco', slug: 'tzuco', category: 'restaurant', metros: ['chicago'] },
  { name: 'Momento Cantina', slug: 'momentocantina', category: 'restaurant', metros: ['chicago'] },
  { name: 'Matilda Restaurant', slug: 'matildarestaurant', category: 'restaurant', metros: ['chicago'] },
  { name: 'XOCO', slug: 'xoco', category: 'restaurant', metros: ['chicago'] },
  { name: 'La Luna', slug: 'laluna', category: 'restaurant', metros: ['chicago'] },
  { name: 'Frontera Grill', slug: 'fronteragrill', category: 'restaurant', metros: ['chicago'] },
  { name: 'Green Street Smoked Meats', slug: 'greenstreetsmokedmeats', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoque BBQ', slug: 'smoquebbq', category: 'korean', metros: ['chicago'] },
  { name: 'Bub City', slug: 'bubcity', category: 'restaurant', metros: ['chicago'] },
  { name: 'Chubby Cattle BBQ | Chicago', slug: 'chubbycattlebbqchicago', category: 'korean', metros: ['chicago'] },
  { name: 'Offset BBQ', slug: 'offsetbbq', category: 'korean', metros: ['chicago'] },
  { name: 'Honky Tonk BBQ / The Tonk', slug: 'honkytonkbbqthetonk', category: 'korean', metros: ['chicago'] },
  { name: 'Chicago Q', slug: 'chicagoq', category: 'restaurant', metros: ['chicago'] },
  { name: 'Carson’s Prime Steaks & Famous Barbecue – Chicago (Streeterville)', slug: 'carsonsprimesteaksfamousbarbecuechicagos', category: 'restaurant', metros: ['chicago'] },
  { name: 'Soul & Smoke - Avondale at Rockwell on the River', slug: 'soulsmoke-avondaleatrockwellontheriver', category: 'restaurant', metros: ['chicago'] },
  { name: 'Smoke Daddy BBQ - Wrigleyville', slug: 'smokedaddybbq-wrigleyville', category: 'korean', metros: ['chicago'] },
];

export const DENVER_RESTAURANTS: RestaurantData[] = [
  { name: 'The Plimoth', slug: 'theplimoth', category: 'restaurant', metros: ['denver'] },
  { name: 'The Denver Central Market', slug: 'thedenvercentralmarket', category: 'restaurant', metros: ['denver'] },
  { name: 'Temaki Den', slug: 'temakiden', category: 'restaurant', metros: ['denver'] },
  { name: 'Point Easy Denver', slug: 'pointeasydenver', category: 'restaurant', metros: ['denver'] },
  { name: 'major tom', slug: 'majortom', category: 'restaurant', metros: ['denver'] },
  { name: 'Federales Tacos & Tequila - RiNo, Denver', slug: 'federalestacostequila-rinodenver', category: 'mexican', metros: ['denver'] },
  { name: 'Alma Fonda Fina', slug: 'almafondafina', category: 'restaurant', metros: ['denver'] },
  { name: 'Nocturne', slug: 'nocturne', category: 'restaurant', metros: ['denver'] },
  { name: 'Cart-Driver RiNo', slug: 'cart-driverrino', category: 'restaurant', metros: ['denver'] },
  { name: 'Work & Class', slug: 'workclass', category: 'restaurant', metros: ['denver'] },
  { name: 'BearLeek', slug: 'bearleek', category: 'restaurant', metros: ['denver'] },
];

export const HOUSTON_RESTAURANTS: RestaurantData[] = [
  { name: 'Lost & Found', slug: 'lostfound', category: 'restaurant', metros: ['houston'] },
  { name: 'Aquarium Restaurant', slug: 'aquariumrestaurant', category: 'restaurant', metros: ['houston'] },
  { name: 'Bungalow', slug: 'bungalow', category: 'restaurant', metros: ['houston'] },
  { name: 'State of Grace', slug: 'stateofgrace', category: 'restaurant', metros: ['houston'] },
  { name: 'Lucille\'s', slug: 'lucilles', category: 'restaurant', metros: ['houston'] },
  { name: 'Brenner\'s on the Bayou', slug: 'brennersonthebayou', category: 'restaurant', metros: ['houston'] },
  { name: 'Hull & Oak', slug: 'hulloak', category: 'restaurant', metros: ['houston'] },
  { name: 'Traveler\'s Table', slug: 'travelerstable', category: 'restaurant', metros: ['houston'] },
  { name: 'Taste of Texas', slug: 'tasteoftexas', category: 'restaurant', metros: ['houston'] },
  { name: 'JOEY Uptown', slug: 'joeyuptown', category: 'restaurant', metros: ['houston'] },
  { name: 'Postino Montrose', slug: 'postinomontrose', category: 'restaurant', metros: ['houston'] },
  { name: 'The Pit Room', slug: 'thepitroom', category: 'restaurant', metros: ['houston'] },
  { name: 'Fielding\'s Steak', slug: 'fieldingssteak', category: 'restaurant', metros: ['houston'] },
  { name: 'Roost', slug: 'roost', category: 'restaurant', metros: ['houston'] },
  { name: 'Little’s Oyster Bar', slug: 'littlesoysterbar', category: 'seafood', metros: ['houston'] },
  { name: 'Nobie\'s', slug: 'nobies', category: 'restaurant', metros: ['houston'] },
  { name: '93\' Til', slug: '93til', category: 'restaurant', metros: ['houston'] },
  { name: 'Hugo\'s', slug: 'hugos', category: 'restaurant', metros: ['houston'] },
];

export const LA_RESTAURANTS: RestaurantData[] = [
  { name: 'Perch', slug: 'perch', category: 'restaurant', metros: ['la'] },
  { name: 'JOEY DTLA', slug: 'joeydtla', category: 'restaurant', metros: ['la'] },
  { name: 'Little Beast Restaurant', slug: 'littlebeastrestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Yamashiro Hollywood', slug: 'yamashirohollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Musso & Frank Grill', slug: 'mussofrankgrill', category: 'restaurant', metros: ['la'] },
  { name: 'Providence', slug: 'providence', category: 'restaurant', metros: ['la'] },
  { name: 'La Boheme', slug: 'laboheme', category: 'restaurant', metros: ['la'] },
  { name: 'Superba Food + Bread Hollywood', slug: 'superbafoodbreadhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'The Little Door', slug: 'thelittledoor', category: 'restaurant', metros: ['la'] },
  { name: 'Girl & the Goat Los Angeles', slug: 'girlthegoatlosangeles', category: 'restaurant', metros: ['la'] },
  { name: 'Jemma Hollywood', slug: 'jemmahollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Running Goose', slug: 'runninggoose', category: 'restaurant', metros: ['la'] },
  { name: 'Mother Wolf', slug: 'motherwolf', category: 'restaurant', metros: ['la'] },
  { name: 'UOVO Santa Monica', slug: 'uovosantamonica', category: 'restaurant', metros: ['la'] },
  { name: 'Guelaguetza Restaurant', slug: 'guelaguetzarestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Holbox', slug: 'holbox', category: 'restaurant', metros: ['la'] },
  { name: 'El Cholo - The Original', slug: 'elcholo-theoriginal', category: 'restaurant', metros: ['la'] },
  { name: 'Guisados', slug: 'guisados', category: 'restaurant', metros: ['la'] },
  { name: 'Sol Agave LA LIVE', slug: 'solagavelalive', category: 'restaurant', metros: ['la'] },
  { name: 'Gracias Madre', slug: 'graciasmadre', category: 'restaurant', metros: ['la'] },
  { name: 'El Compadre Restaurant of Hollywood', slug: 'elcompadrerestaurantofhollywood', category: 'restaurant', metros: ['la'] },
  { name: 'Casita Del Campo', slug: 'casitadelcampo', category: 'restaurant', metros: ['la'] },
  { name: 'Javier\'s', slug: 'javiers', category: 'restaurant', metros: ['la'] },
  { name: 'Madre Restaurant', slug: 'madrerestaurant', category: 'restaurant', metros: ['la'] },
  { name: 'Hae Jang Chon Korean BBQ Restaurant', slug: 'haejangchonkoreanbbqrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Sun Nong Dan', slug: 'sunnongdan', category: 'restaurant', metros: ['la'] },
  { name: 'Jumsim', slug: 'jumsim', category: 'restaurant', metros: ['la'] },
  { name: 'Hanu K BBQ', slug: 'hanukbbq', category: 'korean', metros: ['la'] },
  { name: 'Park\'s BBQ', slug: 'parksbbq', category: 'korean', metros: ['la'] },
  { name: 'Jun Won Dak IG @junwon_la', slug: 'junwondakigjunwonla', category: 'restaurant', metros: ['la'] },
  { name: 'Kobawoo House', slug: 'kobawoohouse', category: 'restaurant', metros: ['la'] },
  { name: 'HOJOKBAN LA', slug: 'hojokbanla', category: 'restaurant', metros: ['la'] },
  { name: '여기요 YeoGiYo 한식전문 | Premium Korean Restaurant', slug: 'yeogiyopremiumkoreanrestaurant', category: 'korean', metros: ['la'] },
  { name: 'Baroo', slug: 'baroo', category: 'restaurant', metros: ['la'] },
  { name: 'Bacari Silverlake', slug: 'bacarisilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Sonmari', slug: 'sonmari', category: 'restaurant', metros: ['la'] },
  { name: 'Pine and Crane Silverlake', slug: 'pineandcranesilverlake', category: 'restaurant', metros: ['la'] },
  { name: 'Botanica Restaurant and Market', slug: 'botanicarestaurantandmarket', category: 'restaurant', metros: ['la'] },
  { name: 'Izakaya Osen', slug: 'izakayaosen', category: 'restaurant', metros: ['la'] },
  { name: 'Tacolina', slug: 'tacolina', category: 'mexican', metros: ['la'] },
  { name: 'Ceviche Project', slug: 'cevicheproject', category: 'restaurant', metros: ['la'] },
  { name: 'The Black Cat', slug: 'theblackcat', category: 'restaurant', metros: ['la'] },
  { name: 'Santo Silverlake', slug: 'santosilverlake', category: 'restaurant', metros: ['la'] },
];

export const MIAMI_RESTAURANTS: RestaurantData[] = [
  { name: 'Komodo Miami', slug: 'komodomiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Moxies Miami Restaurant', slug: 'moxiesmiamirestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Tua Cucina Brickell', slug: 'casatuacucinabrickell', category: 'restaurant', metros: ['miami'] },
  { name: 'Nikki Beach Miami Beach', slug: 'nikkibeachmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Old\'s Havana Cuban Bar & Cocina', slug: 'oldshavanacubanbarcocina', category: 'restaurant', metros: ['miami'] },
  { name: 'Versailles Restaurant Cuban Cuisine', slug: 'versaillesrestaurantcubancuisine', category: 'restaurant', metros: ['miami'] },
  { name: 'La Mulata | Cuban Restaurant Miami Beach', slug: 'lamulatacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Esquina Cubana | Cuban Restaurant Miami Beach', slug: 'esquinacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Havana Vieja | Latin Restaurant Miami Beach', slug: 'havanaviejalatinrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Sala\'o Cuban Restaurant & Bar - Live music', slug: 'salaocubanrestaurantbar-livemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Marabu Restaurant', slug: 'maraburestaurant', category: 'restaurant', metros: ['miami'] },
  { name: 'Alma Cubana | Cuban Restaurant Miami Beach', slug: 'almacubanacubanrestaurantmiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Casa Cubana | Restaurant & Live Music', slug: 'casacubanarestaurantlivemusic', category: 'restaurant', metros: ['miami'] },
  { name: 'Little Havana', slug: 'littlehavana', category: 'restaurant', metros: ['miami'] },
  { name: 'Mayami Wynwood', slug: 'mayamiwynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'Sha Wynwood', slug: 'shawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'R House Wynwood', slug: 'rhousewynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'BAKAN', slug: 'bakan', category: 'restaurant', metros: ['miami'] },
  { name: 'Astra Miami Rooftop', slug: 'astramiamirooftop', category: 'restaurant', metros: ['miami'] },
  { name: 'Le Chick Miami', slug: 'lechickmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Ossobuco Miami - Steak house', slug: 'ossobucomiami-steakhouse', category: 'restaurant', metros: ['miami'] },
  { name: 'KYU Miami', slug: 'kyumiami', category: 'restaurant', metros: ['miami'] },
  { name: 'Manta Wynwood', slug: 'mantawynwood', category: 'restaurant', metros: ['miami'] },
  { name: 'MIAM CAFE-WYNWOOD', slug: 'miamcafe-wynwood', category: 'cafe', metros: ['miami'] },
  { name: 'Joe\'s Stone Crab', slug: 'joesstonecrab', category: 'restaurant', metros: ['miami'] },
  { name: 'Mercato della Pescheria Miami Beach', slug: 'mercatodellapescheriamiamibeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Españolita Miami Beach 🌹💃SEAFOOD&STEAKHOUSE', slug: 'espaolitamiamibeachseafoodsteakhouse', category: 'seafood', metros: ['miami'] },
  { name: 'Nettuno Italian Seafood & Oysters', slug: 'nettunoitalianseafoodoysters', category: 'seafood', metros: ['miami'] },
  { name: 'A Fish Called Avalon', slug: 'afishcalledavalon', category: 'seafood', metros: ['miami'] },
  { name: 'CORALLO 🇮🇹 Amalfi coast', slug: 'coralloamalficoast', category: 'restaurant', metros: ['miami'] },
  { name: 'Rusty Pelican Miami', slug: 'rustypelicanmiami', category: 'restaurant', metros: ['miami'] },
  { name: 'CVI.CHE 105 South Beach', slug: 'cviche105southbeach', category: 'restaurant', metros: ['miami'] },
  { name: 'Osteria Positano', slug: 'osteriapositano', category: 'restaurant', metros: ['miami'] },
  { name: 'CJ\'s Crab Shack', slug: 'cjscrabshack', category: 'restaurant', metros: ['miami'] },
  { name: 'Felice Brickell', slug: 'felicebrickell', category: 'restaurant', metros: ['miami'] },
];

export const NASHVILLE_RESTAURANTS: RestaurantData[] = [
  { name: 'The Finch', slug: 'thefinch', category: 'restaurant', metros: ['nashville'] },
  { name: 'Puckett\'s Restaurant', slug: 'puckettsrestaurant', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Stillery', slug: 'thestillery', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Loveless Cafe', slug: 'thelovelesscafe', category: 'cafe', metros: ['nashville'] },
  { name: 'Lockeland Table', slug: 'lockelandtable', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Hampton Social - Nashville', slug: 'thehamptonsocial-nashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Treehouse Nashville', slug: 'thetreehousenashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'Milk & Honey Gulch', slug: 'milkhoneygulch', category: 'restaurant', metros: ['nashville'] },
  { name: 'Harriet\'s Rooftop', slug: 'harrietsrooftop', category: 'restaurant', metros: ['nashville'] },
  { name: 'The Twelve Thirty Club', slug: 'thetwelvethirtyclub', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Midtown', slug: 'hattiebshotchicken-nashville-midtown', category: 'restaurant', metros: ['nashville'] },
  { name: 'Red\'s Hot Chicken', slug: 'redshotchicken', category: 'restaurant', metros: ['nashville'] },
  { name: 'Champy\'s Nashville', slug: 'champysnashville', category: 'restaurant', metros: ['nashville'] },
  { name: 'Prince\'s Hot Chicken Shack South', slug: 'princeshotchickenshacksouth', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Lower Broadway', slug: 'hattiebshotchicken-nashville-lowerbroadw', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - West', slug: 'hattiebshotchicken-nashville-west', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hattie B\'s Hot Chicken - Nashville - Melrose', slug: 'hattiebshotchicken-nashville-melrose', category: 'restaurant', metros: ['nashville'] },
  { name: 'Helen\'s Hot Chicken', slug: 'helenshotchicken', category: 'restaurant', metros: ['nashville'] },
  { name: 'Hella Hot Chicken Donelson', slug: 'hellahotchickendonelson', category: 'restaurant', metros: ['nashville'] },
  { name: 'Pepperfire Hot Chicken', slug: 'pepperfirehotchicken', category: 'restaurant', metros: ['nashville'] },
];

export const NOLA_RESTAURANTS: RestaurantData[] = [
  { name: 'Brennan\'s', slug: 'brennans', category: 'restaurant', metros: ['nola'] },
  { name: 'Napoleon House', slug: 'napoleonhouse', category: 'restaurant', metros: ['nola'] },
  { name: 'Cochon Restaurant', slug: 'cochonrestaurant', category: 'restaurant', metros: ['nola'] },
  { name: 'Muriel\'s Jackson Square', slug: 'murielsjacksonsquare', category: 'restaurant', metros: ['nola'] },
  { name: 'Commander\'s Palace', slug: 'commanderspalace', category: 'restaurant', metros: ['nola'] },
  { name: 'GW Fins', slug: 'gwfins', category: 'restaurant', metros: ['nola'] },
  { name: 'Cochon Butcher', slug: 'cochonbutcher', category: 'restaurant', metros: ['nola'] },
  { name: 'Olde Nola Cookery', slug: 'oldenolacookery', category: 'restaurant', metros: ['nola'] },
  { name: 'Bourbon House', slug: 'bourbonhouse', category: 'restaurant', metros: ['nola'] },
  { name: 'Luke', slug: 'luke', category: 'restaurant', metros: ['nola'] },
  { name: 'zesty creole', slug: 'zestycreole', category: 'restaurant', metros: ['nola'] },
  { name: 'Mulate\'s | The Original Cajun Restaurant', slug: 'mulatestheoriginalcajunrestaurant', category: 'restaurant', metros: ['nola'] },
  { name: 'Creole House Restaurant & Oyster Bar', slug: 'creolehouserestaurantoysterbar', category: 'seafood', metros: ['nola'] },
  { name: 'Cajun Seafood', slug: 'cajunseafood', category: 'seafood', metros: ['nola'] },
  { name: 'The Original Pierre Maspero\'s', slug: 'theoriginalpierremasperos', category: 'restaurant', metros: ['nola'] },
  { name: 'Mambo’s', slug: 'mambos', category: 'restaurant', metros: ['nola'] },
  { name: 'Hot N Cajun Boil House', slug: 'hotncajunboilhouse', category: 'restaurant', metros: ['nola'] },
];

export const NYC_RESTAURANTS: RestaurantData[] = [
  { name: 'Monkey Bar', slug: 'monkeybar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sungold Restaurant Brooklyn NY (Arlo Williamsburg)', slug: 'sungoldrestaurantbrooklynnyarlowilliamsb', category: 'restaurant', metros: ['nyc'] },
  { name: 'Recette', slug: 'recette', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hole In The Wall', slug: 'holeinthewall', category: 'restaurant', metros: ['nyc'] },
  { name: 'The River Café', slug: 'therivercaf', category: 'restaurant', metros: ['nyc'] },
  { name: 'Cornbread Brooklyn', slug: 'cornbreadbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fandi Mata', slug: 'fandimata', category: 'restaurant', metros: ['nyc'] },
  { name: 'LILLI RESTAURANT', slug: 'lillirestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sunday In Brooklyn', slug: 'sundayinbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Evelina', slug: 'evelina', category: 'restaurant', metros: ['nyc'] },
  { name: 'Francie', slug: 'francie', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Alcove', slug: 'thealcove', category: 'restaurant', metros: ['nyc'] },
  { name: 'Park Side Restaurant', slug: 'parksiderestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Casa Enrique', slug: 'casaenrique', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mom\'s Kitchen & Bar', slug: 'momskitchenbar', category: 'restaurant', metros: ['nyc'] },
  { name: '(aged.)', slug: 'aged', category: 'restaurant', metros: ['nyc'] },
  { name: 'London Lennie\'s', slug: 'londonlennies', category: 'restaurant', metros: ['nyc'] },
  { name: 'Nan Xiang Soup Dumplings - Flushing', slug: 'nanxiangsoupdumplings-flushing', category: 'restaurant', metros: ['nyc'] },
  { name: 'Florence Prime Diner', slug: 'florenceprimediner', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rainhas Churrascaria', slug: 'rainhaschurrascaria', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fogo de Chão Brazilian Steakhouse', slug: 'fogodechobraziliansteakhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Joe\'s Pizza Broadway', slug: 'joespizzabroadway', category: 'pizza', metros: ['nyc'] },
  { name: 'Nuovo York Pizza', slug: 'nuovoyorkpizza', category: 'pizza', metros: ['nyc'] },
  { name: 'John\'s of Bleecker Street', slug: 'johnsofbleeckerstreet', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rubirosa', slug: 'rubirosa', category: 'restaurant', metros: ['nyc'] },
  { name: 'Lombardi\'s', slug: 'lombardis', category: 'restaurant', metros: ['nyc'] },
  { name: 'NY Pizza Suprema', slug: 'nypizzasuprema', category: 'pizza', metros: ['nyc'] },
  { name: 'OLIO E PIÙ', slug: 'olioepi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Don Antonio', slug: 'donantonio', category: 'restaurant', metros: ['nyc'] },
  { name: 'Kesté Pizza e Vino', slug: 'kestpizzaevino', category: 'pizza', metros: ['nyc'] },
  { name: 'Capizzi', slug: 'capizzi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Jiang Nan NYC', slug: 'jiangnannyc', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shanghai 21', slug: 'shanghai21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Wo Hop', slug: 'wohop', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan', slug: 'thebestsichuan', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都39', slug: 'thebestsichuan39', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都21', slug: 'thebestsichuan21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Chi Restaurant & Bar', slug: 'chirestaurantbar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Uncle Lou 快樂人', slug: 'unclelou', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mountain House', slug: 'mountainhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hutong New York', slug: 'hutongnewyork', category: 'restaurant', metros: ['nyc'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['nyc'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['nyc'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['nyc'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['nyc'] },
  { name: 'Au Cheval', slug: 'aucheval', category: 'restaurant', metros: ['nyc'] },
  { name: '5 Napkin Burger', slug: '5napkinburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger Theater District | Hamburger restaurant Bar', slug: 'blackironburgertheaterdistricthamburgerr', category: 'burgers', metros: ['nyc'] },
  { name: 'Jackson Hole Burgers', slug: 'jacksonholeburgers', category: 'burgers', metros: ['nyc'] },
  { name: 'Bareburger', slug: 'bareburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger', slug: 'blackironburger', category: 'burgers', metros: ['nyc'] },
  { name: 'burger joint', slug: 'burgerjoint', category: 'burgers', metros: ['nyc'] },
  { name: 'Lovely\'s Old Fashioned', slug: 'lovelysoldfashioned', category: 'restaurant', metros: ['nyc'] },
  { name: 'Thai Villa', slug: 'thaivilla', category: 'thai', metros: ['nyc'] },
  { name: 'Mitr Thai Restaurant', slug: 'mitrthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'Elephant Ear', slug: 'elephantear', category: 'restaurant', metros: ['nyc'] },
  { name: 'Soothr', slug: 'soothr', category: 'restaurant', metros: ['nyc'] },
  { name: 'Up Thai', slug: 'upthai', category: 'thai', metros: ['nyc'] },
  { name: 'Hey Thai', slug: 'heythai', category: 'thai', metros: ['nyc'] },
  { name: 'Chalong Southern Thai', slug: 'chalongsouthernthai', category: 'thai', metros: ['nyc'] },
  { name: 'THEP Thai Restaurant', slug: 'thepthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'LumLum', slug: 'lumlum', category: 'restaurant', metros: ['nyc'] },
  { name: 'Pranakhon', slug: 'pranakhon', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Nonnino', slug: 'osterianonnino', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Pecora Bianca SoHo', slug: 'lapecorabiancasoho', category: 'restaurant', metros: ['nyc'] },
  { name: 'Carmine\'s - Time Square', slug: 'carmines-timesquare', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria La Baia', slug: 'osterialabaia', category: 'restaurant', metros: ['nyc'] },
  { name: 'Tony\'s Di Napoli', slug: 'tonysdinapoli', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Barocca', slug: 'osteriabarocca', category: 'restaurant', metros: ['nyc'] },
  { name: 'Scarpetta', slug: 'scarpetta', category: 'restaurant', metros: ['nyc'] },
  { name: 'Ci Siamo', slug: 'cisiamo', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Lanterna di Vittorio', slug: 'lalanternadivittorio', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOLITA', slug: 'lolita', category: 'restaurant', metros: ['nyc'] },
  { name: 'Amor Loco', slug: 'amorloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rosa Mexicano', slug: 'rosamexicano', category: 'mexican', metros: ['nyc'] },
  { name: 'Cosme', slug: 'cosme', category: 'restaurant', metros: ['nyc'] },
  { name: 'Vida Verde - Tequila Bar', slug: 'vidaverde-tequilabar', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Esquina Brasserie', slug: 'laesquinabrasserie', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mamasita Bar & Grill', slug: 'mamasitabargrill', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOS TACOS No.1', slug: 'lostacosno1', category: 'mexican', metros: ['nyc'] },
  { name: 'Toro Loco', slug: 'toroloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Toloache', slug: 'toloache', category: 'restaurant', metros: ['nyc'] },
];

export const PHILLY_RESTAURANTS: RestaurantData[] = [
  { name: 'The Dandelion', slug: 'thedandelion', category: 'deli', metros: ['philly'] },
  { name: 'Talula\'s Garden', slug: 'talulasgarden', category: 'restaurant', metros: ['philly'] },
  { name: 'The Love.', slug: 'thelove', category: 'restaurant', metros: ['philly'] },
  { name: 'Harper\'s Garden', slug: 'harpersgarden', category: 'restaurant', metros: ['philly'] },
  { name: 'Wilder', slug: 'wilder', category: 'restaurant', metros: ['philly'] },
  { name: 'Jean-Georges Philadelphia', slug: 'jean-georgesphiladelphia', category: 'restaurant', metros: ['philly'] },
  { name: 'Butcher and Singer', slug: 'butcherandsinger', category: 'restaurant', metros: ['philly'] },
  { name: 'Harp & Crown', slug: 'harpcrown', category: 'restaurant', metros: ['philly'] },
  { name: 'Little Nonna\'s', slug: 'littlenonnas', category: 'restaurant', metros: ['philly'] },
  { name: 'Skyhigh', slug: 'skyhigh', category: 'restaurant', metros: ['philly'] },
  { name: 'Osteria Ama Philly', slug: 'osteriaamaphilly', category: 'restaurant', metros: ['philly'] },
  { name: 'Wm. Mulherin’s Sons', slug: 'wmmulherinssons', category: 'restaurant', metros: ['philly'] },
  { name: 'Suraya Restaurant', slug: 'surayarestaurant', category: 'restaurant', metros: ['philly'] },
  { name: 'Fabrika', slug: 'fabrika', category: 'restaurant', metros: ['philly'] },
  { name: 'LMNO', slug: 'lmno', category: 'restaurant', metros: ['philly'] },
  { name: 'Elwood', slug: 'elwood', category: 'restaurant', metros: ['philly'] },
  { name: 'Front Street Cafe', slug: 'frontstreetcafe', category: 'cafe', metros: ['philly'] },
  { name: 'Forest & Main Fishtown', slug: 'forestmainfishtown', category: 'seafood', metros: ['philly'] },
  { name: 'Fette Sau', slug: 'fettesau', category: 'restaurant', metros: ['philly'] },
  { name: 'Middle Child Clubhouse', slug: 'middlechildclubhouse', category: 'restaurant', metros: ['philly'] },
  { name: 'Two Robbers Fishtown', slug: 'tworobbersfishtown', category: 'seafood', metros: ['philly'] },
];

export const SEATTLE_RESTAURANTS: RestaurantData[] = [
  { name: 'Can Can Seattle: A Culinary Cabaret', slug: 'cancanseattleaculinarycabaret', category: 'restaurant', metros: ['seattle'] },
  { name: 'Kedai Makan Capitol Hill', slug: 'kedaimakancapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'Spinasse', slug: 'spinasse', category: 'restaurant', metros: ['seattle'] },
  { name: 'The Pink Door', slug: 'thepinkdoor', category: 'restaurant', metros: ['seattle'] },
  { name: 'Momiji Capitol Hill', slug: 'momijicapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'Nue', slug: 'nue', category: 'restaurant', metros: ['seattle'] },
  { name: 'Terra Plata', slug: 'terraplata', category: 'restaurant', metros: ['seattle'] },
  { name: 'Taurus Ox', slug: 'taurusox', category: 'restaurant', metros: ['seattle'] },
  { name: 'Ba Bar Capitol Hill', slug: 'babarcapitolhill', category: 'restaurant', metros: ['seattle'] },
  { name: 'MariPili Tapas Bar', slug: 'maripilitapasbar', category: 'restaurant', metros: ['seattle'] },
  { name: 'Taneda', slug: 'taneda', category: 'restaurant', metros: ['seattle'] },
];

export const SF_RESTAURANTS: RestaurantData[] = [
  { name: 'Nopa', slug: 'nopa', category: 'restaurant', metros: ['sf'] },
  { name: 'The View Lounge', slug: 'theviewlounge', category: 'restaurant', metros: ['sf'] },
  { name: 'Zeitgeist', slug: 'zeitgeist', category: 'restaurant', metros: ['sf'] },
  { name: 'Absinthe Brasserie & Bar', slug: 'absinthebrasseriebar', category: 'restaurant', metros: ['sf'] },
  { name: 'Lazy Bear', slug: 'lazybear', category: 'restaurant', metros: ['sf'] },
  { name: 'Bottega', slug: 'bottega', category: 'restaurant', metros: ['sf'] },
  { name: 'The Morris', slug: 'themorris', category: 'restaurant', metros: ['sf'] },
  { name: 'The Rabbit Hole', slug: 'therabbithole', category: 'restaurant', metros: ['sf'] },
  { name: 'La Taqueria', slug: 'lataqueria', category: 'restaurant', metros: ['sf'] },
  { name: 'Beretta Valencia', slug: 'berettavalencia', category: 'restaurant', metros: ['sf'] },
  { name: 'Rintaro', slug: 'rintaro', category: 'restaurant', metros: ['sf'] },
  { name: 'Foreign Cinema', slug: 'foreigncinema', category: 'restaurant', metros: ['sf'] },
  { name: 'Sangria & Salt', slug: 'sangriasalt', category: 'restaurant', metros: ['sf'] },
  { name: 'Lolinda', slug: 'lolinda', category: 'restaurant', metros: ['sf'] },
];

