// Auto-generated via Google Places API — 2026-02-12T12:23:06.530Z
// 86 restaurants in NYC

export const NYC_RESTAURANTS = [
  { name: 'Monkey Bar', slug: 'monkeybar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sungold Restaurant Brooklyn NY (Arlo Williamsburg)', slug: 'sungoldrestaurantbrooklynnyarlowilliamsb', category: 'restaurant', metros: ['nyc'] },
  { name: 'Recette', slug: 'recette', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hole In The Wall', slug: 'holeinthewall', category: 'restaurant', metros: ['nyc'] },
  { name: 'The River Café', slug: 'therivercaf', category: 'restaurant', metros: ['nyc'] },
  { name: 'Cornbread Brooklyn', slug: 'cornbreadbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fandi Mata', slug: 'fandimata', category: 'restaurant', metros: ['nyc'] },
  { name: 'LILLI RESTAURANT', slug: 'lillirestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Sunday In Brooklyn', slug: 'sundayinbrooklyn', category: 'restaurant', metros: ['nyc'] },
  { name: 'Evelina', slug: 'evelina', category: 'restaurant', metros: ['nyc'] },
  { name: 'Francie', slug: 'francie', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Alcove', slug: 'thealcove', category: 'restaurant', metros: ['nyc'] },
  { name: 'Park Side Restaurant', slug: 'parksiderestaurant', category: 'restaurant', metros: ['nyc'] },
  { name: 'Casa Enrique', slug: 'casaenrique', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mom\'s Kitchen & Bar', slug: 'momskitchenbar', category: 'restaurant', metros: ['nyc'] },
  { name: '(aged.)', slug: 'aged', category: 'restaurant', metros: ['nyc'] },
  { name: 'London Lennie\'s', slug: 'londonlennies', category: 'restaurant', metros: ['nyc'] },
  { name: 'Nan Xiang Soup Dumplings - Flushing', slug: 'nanxiangsoupdumplings-flushing', category: 'restaurant', metros: ['nyc'] },
  { name: 'Florence Prime Diner', slug: 'florenceprimediner', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rainhas Churrascaria', slug: 'rainhaschurrascaria', category: 'restaurant', metros: ['nyc'] },
  { name: 'Fogo de Chão Brazilian Steakhouse', slug: 'fogodechobraziliansteakhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Joe\'s Pizza Broadway', slug: 'joespizzabroadway', category: 'pizza', metros: ['nyc'] },
  { name: 'Nuovo York Pizza', slug: 'nuovoyorkpizza', category: 'pizza', metros: ['nyc'] },
  { name: 'John\'s of Bleecker Street', slug: 'johnsofbleeckerstreet', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rubirosa', slug: 'rubirosa', category: 'restaurant', metros: ['nyc'] },
  { name: 'Lombardi\'s', slug: 'lombardis', category: 'restaurant', metros: ['nyc'] },
  { name: 'NY Pizza Suprema', slug: 'nypizzasuprema', category: 'pizza', metros: ['nyc'] },
  { name: 'OLIO E PIÙ', slug: 'olioepi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Don Antonio', slug: 'donantonio', category: 'restaurant', metros: ['nyc'] },
  { name: 'Kesté Pizza e Vino', slug: 'kestpizzaevino', category: 'pizza', metros: ['nyc'] },
  { name: 'Capizzi', slug: 'capizzi', category: 'restaurant', metros: ['nyc'] },
  { name: 'Jiang Nan NYC', slug: 'jiangnannyc', category: 'restaurant', metros: ['nyc'] },
  { name: 'Shanghai 21', slug: 'shanghai21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Wo Hop', slug: 'wohop', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan', slug: 'thebestsichuan', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都39', slug: 'thebestsichuan39', category: 'restaurant', metros: ['nyc'] },
  { name: 'The Best Sichuan 一品成都21', slug: 'thebestsichuan21', category: 'restaurant', metros: ['nyc'] },
  { name: 'Chi Restaurant & Bar', slug: 'chirestaurantbar', category: 'restaurant', metros: ['nyc'] },
  { name: 'Uncle Lou 快樂人', slug: 'unclelou', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mountain House', slug: 'mountainhouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Hutong New York', slug: 'hutongnewyork', category: 'restaurant', metros: ['nyc'] },
  { name: 'Caroline', slug: 'caroline', category: 'restaurant', metros: ['nyc'] },
  { name: 'Two Hands', slug: 'twohands', category: 'restaurant', metros: ['nyc'] },
  { name: 'Corinne Austin', slug: 'corinneaustin', category: 'restaurant', metros: ['nyc'] },
  { name: 'Magnolia Cafe', slug: 'magnoliacafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Another Broken Egg Cafe', slug: 'anotherbrokeneggcafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Josephine House', slug: 'josephinehouse', category: 'restaurant', metros: ['nyc'] },
  { name: 'Day Maker Half Day Cafe', slug: 'daymakerhalfdaycafe', category: 'cafe', metros: ['nyc'] },
  { name: 'Summer on Music Lane', slug: 'summeronmusiclane', category: 'restaurant', metros: ['nyc'] },
  { name: 'Au Cheval', slug: 'aucheval', category: 'restaurant', metros: ['nyc'] },
  { name: '5 Napkin Burger', slug: '5napkinburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger Theater District | Hamburger restaurant Bar', slug: 'blackironburgertheaterdistricthamburgerr', category: 'burgers', metros: ['nyc'] },
  { name: 'Jackson Hole Burgers', slug: 'jacksonholeburgers', category: 'burgers', metros: ['nyc'] },
  { name: 'Bareburger', slug: 'bareburger', category: 'burgers', metros: ['nyc'] },
  { name: 'Black Iron Burger', slug: 'blackironburger', category: 'burgers', metros: ['nyc'] },
  { name: 'burger joint', slug: 'burgerjoint', category: 'burgers', metros: ['nyc'] },
  { name: 'Lovely\'s Old Fashioned', slug: 'lovelysoldfashioned', category: 'restaurant', metros: ['nyc'] },
  { name: 'Thai Villa', slug: 'thaivilla', category: 'thai', metros: ['nyc'] },
  { name: 'Mitr Thai Restaurant', slug: 'mitrthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'Elephant Ear', slug: 'elephantear', category: 'restaurant', metros: ['nyc'] },
  { name: 'Soothr', slug: 'soothr', category: 'restaurant', metros: ['nyc'] },
  { name: 'Up Thai', slug: 'upthai', category: 'thai', metros: ['nyc'] },
  { name: 'Hey Thai', slug: 'heythai', category: 'thai', metros: ['nyc'] },
  { name: 'Chalong Southern Thai', slug: 'chalongsouthernthai', category: 'thai', metros: ['nyc'] },
  { name: 'THEP Thai Restaurant', slug: 'thepthairestaurant', category: 'thai', metros: ['nyc'] },
  { name: 'LumLum', slug: 'lumlum', category: 'restaurant', metros: ['nyc'] },
  { name: 'Pranakhon', slug: 'pranakhon', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Nonnino', slug: 'osterianonnino', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Pecora Bianca SoHo', slug: 'lapecorabiancasoho', category: 'restaurant', metros: ['nyc'] },
  { name: 'Carmine\'s - Time Square', slug: 'carmines-timesquare', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria La Baia', slug: 'osterialabaia', category: 'restaurant', metros: ['nyc'] },
  { name: 'Tony\'s Di Napoli', slug: 'tonysdinapoli', category: 'restaurant', metros: ['nyc'] },
  { name: 'Osteria Barocca', slug: 'osteriabarocca', category: 'restaurant', metros: ['nyc'] },
  { name: 'Scarpetta', slug: 'scarpetta', category: 'restaurant', metros: ['nyc'] },
  { name: 'Ci Siamo', slug: 'cisiamo', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Lanterna di Vittorio', slug: 'lalanternadivittorio', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOLITA', slug: 'lolita', category: 'restaurant', metros: ['nyc'] },
  { name: 'Amor Loco', slug: 'amorloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Rosa Mexicano', slug: 'rosamexicano', category: 'mexican', metros: ['nyc'] },
  { name: 'Cosme', slug: 'cosme', category: 'restaurant', metros: ['nyc'] },
  { name: 'Vida Verde - Tequila Bar', slug: 'vidaverde-tequilabar', category: 'restaurant', metros: ['nyc'] },
  { name: 'La Esquina Brasserie', slug: 'laesquinabrasserie', category: 'restaurant', metros: ['nyc'] },
  { name: 'Mamasita Bar & Grill', slug: 'mamasitabargrill', category: 'restaurant', metros: ['nyc'] },
  { name: 'LOS TACOS No.1', slug: 'lostacosno1', category: 'mexican', metros: ['nyc'] },
  { name: 'Toro Loco', slug: 'toroloco', category: 'restaurant', metros: ['nyc'] },
  { name: 'Toloache', slug: 'toloache', category: 'restaurant', metros: ['nyc'] },
];
