import type { CampusConfig } from './CampusPage';

export const CAMPUS_CONFIGS: Record<string, CampusConfig> = {
  'tamu': {
    slug: 'tamu',
    schoolName: 'Texas A&M',
    shortName: 'A&M',
    emoji: '👍',
    mascot: 'Aggies',
    city: 'College Station',
    tagline: 'Gig \'em and save',
    restaurants: [
      { name: "Layne's Chicken Fingers", category: "Chicken", savings: "$3-5" },
      { name: "Fuego", category: "Tex-Mex", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Grub Burger Bar", category: "Burgers", savings: "$4-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pizza Hut", category: "Pizza", savings: "$3-5" },
    ],
    totalRestaurants: 45,
    cityRestaurants: 280,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Gig \'em 👍',
  },
  'txst': {
    slug: 'txst',
    schoolName: 'Texas State',
    shortName: 'Texas State',
    emoji: '🐱',
    mascot: 'Bobcats',
    city: 'San Marcos',
    tagline: 'Eat up, Bobcats',
    restaurants: [
      { name: "Grins", category: "American", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Jason's Deli", category: "Deli", savings: "$3-5" },
    ],
    totalRestaurants: 35,
    cityRestaurants: 180,
    ordersPerWeek: 3,
    avgSavings: 4,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Eat up, Bobcats 🐱',
  },
  'utd': {
    slug: 'utd',
    schoolName: 'UT Dallas',
    shortName: 'UTD',
    emoji: '☄️',
    mascot: 'Comets',
    city: 'Richardson',
    tagline: 'Smart savings for smart students',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
    ],
    totalRestaurants: 50,
    cityRestaurants: 450,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Whoosh ☄️',
  },
  'utsa': {
    slug: 'utsa',
    schoolName: 'UTSA',
    shortName: 'UTSA',
    emoji: '🐦',
    mascot: 'Roadrunners',
    city: 'San Antonio',
    tagline: 'Birds up, prices down',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Bill Miller Bar-B-Q", category: "BBQ", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
    ],
    totalRestaurants: 50,
    cityRestaurants: 520,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Birds up 🐦',
  },
  'uh': {
    slug: 'uh',
    schoolName: 'University of Houston',
    shortName: 'UH',
    emoji: '🐾',
    mascot: 'Cougars',
    city: 'Houston',
    tagline: 'Go Coogs, save money',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Killen's BBQ", category: "BBQ", savings: "$5-8" },
      { name: "Pepper Twins", category: "Chinese", savings: "$4-6" },
      { name: "The Breakfast Klub", category: "Breakfast", savings: "$4-7" },
    ],
    totalRestaurants: 65,
    cityRestaurants: 850,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Coogs 🐾',
  },
  'tcu': {
    slug: 'tcu',
    schoolName: 'TCU',
    shortName: 'TCU',
    emoji: '🐸',
    mascot: 'Horned Frogs',
    city: 'Fort Worth',
    tagline: 'Riff Ram, save some cash',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Fuzzy's Taco Shop", category: "Tacos", savings: "$3-5" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
    ],
    totalRestaurants: 45,
    cityRestaurants: 400,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Riff Ram 🐸',
  },
  'baylor': {
    slug: 'baylor',
    schoolName: 'Baylor University',
    shortName: 'Baylor',
    emoji: '🐻',
    mascot: 'Bears',
    city: 'Waco',
    tagline: 'Sic \'em and save',
    restaurants: [
      { name: "Vitek's BBQ", category: "BBQ", savings: "$4-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Fuzzy's Taco Shop", category: "Tacos", savings: "$3-5" },
    ],
    totalRestaurants: 35,
    cityRestaurants: 200,
    ordersPerWeek: 3,
    avgSavings: 4,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Sic \'em Bears 🐻',
  },
  'rice': {
    slug: 'rice',
    schoolName: 'Rice University',
    shortName: 'Rice',
    emoji: '🦉',
    mascot: 'Owls',
    city: 'Houston',
    tagline: 'Smart students, smarter ordering',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pepper Twins", category: "Chinese", savings: "$4-6" },
      { name: "The Breakfast Klub", category: "Breakfast", savings: "$4-7" },
    ],
    totalRestaurants: 60,
    cityRestaurants: 850,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Owls 🦉',
  },
};
