import type { CampusConfig } from './CampusPage';

export const CAMPUS_CONFIGS: Record<string, CampusConfig> = {
  'tamu': {
    slug: 'tamu',
    schoolName: 'Texas A&M',
    shortName: 'A&M',
    emoji: '👍',
    mascot: 'Aggies',
    city: 'College Station',
    tagline: 'Gig \'em and save',
    restaurants: [
      { name: "Layne's Chicken Fingers", category: "Chicken", savings: "$3-5" },
      { name: "Fuego", category: "Tex-Mex", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Grub Burger Bar", category: "Burgers", savings: "$4-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pizza Hut", category: "Pizza", savings: "$3-5" },
    ],
    totalRestaurants: 45,
    cityRestaurants: 280,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Gig \'em 👍',
  },
  'txst': {
    slug: 'txst',
    schoolName: 'Texas State',
    shortName: 'Texas State',
    emoji: '🐱',
    mascot: 'Bobcats',
    city: 'San Marcos',
    tagline: 'Eat up, Bobcats',
    restaurants: [
      { name: "Grins", category: "American", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Jason's Deli", category: "Deli", savings: "$3-5" },
    ],
    totalRestaurants: 35,
    cityRestaurants: 180,
    ordersPerWeek: 3,
    avgSavings: 4,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Eat up, Bobcats 🐱',
  },
  'utd': {
    slug: 'utd',
    schoolName: 'UT Dallas',
    shortName: 'UTD',
    emoji: '☄️',
    mascot: 'Comets',
    city: 'Richardson',
    tagline: 'Smart savings for smart students',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
    ],
    totalRestaurants: 50,
    cityRestaurants: 450,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Whoosh ☄️',
  },
  'utsa': {
    slug: 'utsa',
    schoolName: 'UTSA',
    shortName: 'UTSA',
    emoji: '🐦',
    mascot: 'Roadrunners',
    city: 'San Antonio',
    tagline: 'Birds up, prices down',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Bill Miller Bar-B-Q", category: "BBQ", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
    ],
    totalRestaurants: 50,
    cityRestaurants: 520,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Birds up 🐦',
  },
  'uh': {
    slug: 'uh',
    schoolName: 'University of Houston',
    shortName: 'UH',
    emoji: '🐾',
    mascot: 'Cougars',
    city: 'Houston',
    tagline: 'Go Coogs, save money',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Killen's BBQ", category: "BBQ", savings: "$5-8" },
      { name: "Pepper Twins", category: "Chinese", savings: "$4-6" },
      { name: "The Breakfast Klub", category: "Breakfast", savings: "$4-7" },
    ],
    totalRestaurants: 65,
    cityRestaurants: 850,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Coogs 🐾',
  },
  'tcu': {
    slug: 'tcu',
    schoolName: 'TCU',
    shortName: 'TCU',
    emoji: '🐸',
    mascot: 'Horned Frogs',
    city: 'Fort Worth',
    tagline: 'Riff Ram, save some cash',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Fuzzy's Taco Shop", category: "Tacos", savings: "$3-5" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
    ],
    totalRestaurants: 45,
    cityRestaurants: 400,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Riff Ram 🐸',
  },
  'baylor': {
    slug: 'baylor',
    schoolName: 'Baylor University',
    shortName: 'Baylor',
    emoji: '🐻',
    mascot: 'Bears',
    city: 'Waco',
    tagline: 'Sic \'em and save',
    restaurants: [
      { name: "Vitek's BBQ", category: "BBQ", savings: "$4-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Fuzzy's Taco Shop", category: "Tacos", savings: "$3-5" },
    ],
    totalRestaurants: 35,
    cityRestaurants: 200,
    ordersPerWeek: 3,
    avgSavings: 4,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Sic \'em Bears 🐻',
  },
  'rice': {
    slug: 'rice',
    schoolName: 'Rice University',
    shortName: 'Rice',
    emoji: '🦉',
    mascot: 'Owls',
    city: 'Houston',
    tagline: 'Smart students, smarter ordering',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
      { name: "Pluckers", category: "Wings", savings: "$5-8" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pepper Twins", category: "Chinese", savings: "$4-6" },
      { name: "The Breakfast Klub", category: "Breakfast", savings: "$4-7" },
    ],
    totalRestaurants: 60,
    cityRestaurants: 850,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Owls 🦉',
  },
  // === TIER 1: Big schools, deep inventory ===
  'nyu': {
    slug: 'nyu',
    schoolName: 'NYU',
    shortName: 'NYU',
    emoji: '🗽',
    mascot: 'Violets',
    city: 'New York',
    tagline: 'Save money in the city that never sleeps',
    restaurants: [
      { name: "Joe's Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Mamoun's Falafel", category: "Middle Eastern", savings: "$3-5" },
      { name: "Xi'an Famous Foods", category: "Chinese", savings: "$4-6" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Halal Guys", category: "Halal", savings: "$3-5" },
      { name: "Shake Shack", category: "Burgers", savings: "$3-5" },
      { name: "Artichoke Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Dig Inn", category: "Bowls", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
    ],
    totalRestaurants: 80,
    cityRestaurants: 559,
    ordersPerWeek: 4,
    avgSavings: 6,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Violets 🗽',
  },
  'ucla': {
    slug: 'ucla',
    schoolName: 'UCLA',
    shortName: 'UCLA',
    emoji: '🐻',
    mascot: 'Bruins',
    city: 'Los Angeles',
    tagline: 'Bruins save on every order',
    restaurants: [
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Fat Sal's", category: "Sandwiches", savings: "$4-6" },
      { name: "Diddy Riese", category: "Dessert", savings: "$1-3" },
      { name: "Sushi Koo", category: "Sushi", savings: "$5-8" },
      { name: "Zankou Chicken", category: "Mediterranean", savings: "$3-5" },
    ],
    totalRestaurants: 70,
    cityRestaurants: 446,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Bruins 🐻',
  },
  'uchicago': {
    slug: 'uchicago',
    schoolName: 'University of Chicago',
    shortName: 'UChicago',
    emoji: '🔥',
    mascot: 'Maroons',
    city: 'Chicago',
    tagline: 'Where fun comes to save money',
    restaurants: [
      { name: "Giordano's", category: "Deep Dish", savings: "$5-8" },
      { name: "Portillo's", category: "Chicago Style", savings: "$3-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Harold's Chicken", category: "Chicken", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Lou Malnati's", category: "Pizza", savings: "$4-7" },
    ],
    totalRestaurants: 65,
    cityRestaurants: 429,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Maroons 🔥',
  },
  'osu': {
    slug: 'osu',
    schoolName: 'Ohio State',
    shortName: 'OSU',
    emoji: '🌰',
    mascot: 'Buckeyes',
    city: 'Columbus',
    tagline: 'O-H! Save more I-O!',
    restaurants: [
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Condado Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Adriatico's Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
    ],
    totalRestaurants: 45,
    cityRestaurants: 215,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Bucks 🌰',
  },
  'asu': {
    slug: 'asu',
    schoolName: 'Arizona State',
    shortName: 'ASU',
    emoji: '🔱',
    mascot: 'Sun Devils',
    city: 'Tempe',
    tagline: 'Forks up, prices down',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Pedal Haus Brewery", category: "American", savings: "$4-6" },
      { name: "Cornish Pasty Co", category: "British", savings: "$3-5" },
    ],
    totalRestaurants: 55,
    cityRestaurants: 305,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Forks Up 🔱',
  },
  'gatech': {
    slug: 'gatech',
    schoolName: 'Georgia Tech',
    shortName: 'GT',
    emoji: '🐝',
    mascot: 'Yellow Jackets',
    city: 'Atlanta',
    tagline: 'Engineer your savings',
    restaurants: [
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "The Varsity", category: "American", savings: "$3-5" },
      { name: "Antico Pizza", category: "Pizza", savings: "$4-6" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Zaxby's", category: "Chicken", savings: "$3-5" },
    ],
    totalRestaurants: 50,
    cityRestaurants: 261,
    ordersPerWeek: 3,
    avgSavings: 5,
    weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery',
    footerSlogan: 'Go Jackets 🐝',
  },
  // === TIER 2: Strong combo — big schools, deep inventory ===
  'bu': {
    slug: 'bu',
    schoolName: 'Boston University',
    shortName: 'BU',
    emoji: '🐾',
    mascot: 'Terriers',
    city: 'Boston',
    tagline: 'Terriers save on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Al's Cafe", category: "Subs", savings: "$3-5" },
      { name: "Boston Shawarma", category: "Middle Eastern", savings: "$3-5" },
    ],
    totalRestaurants: 60, cityRestaurants: 356, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Terriers 🐾',
  },
  'northeastern': {
    slug: 'northeastern',
    schoolName: 'Northeastern University',
    shortName: 'NEU',
    emoji: '🐾',
    mascot: 'Huskies',
    city: 'Boston',
    tagline: 'Huskies hustle smarter',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Boloco", category: "Burritos", savings: "$3-5" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
    ],
    totalRestaurants: 55, cityRestaurants: 356, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Huskies 🐾',
  },
  'georgetown': {
    slug: 'georgetown',
    schoolName: 'Georgetown University',
    shortName: 'Georgetown',
    emoji: '🐶',
    mascot: 'Hoyas',
    city: 'Washington DC',
    tagline: 'Hoya Saxa, save some cash',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Wiseguy Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Booeymonger", category: "Deli", savings: "$3-5" },
    ],
    totalRestaurants: 55, cityRestaurants: 339, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Hoya Saxa 🐶',
  },
  'gwu': {
    slug: 'gwu',
    schoolName: 'George Washington University',
    shortName: 'GWU',
    emoji: '🏛️',
    mascot: 'Colonials',
    city: 'Washington DC',
    tagline: 'Save like a revolutionary',
    restaurants: [
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Founding Farmers", category: "American", savings: "$5-8" },
      { name: "Duke's Grocery", category: "Brunch", savings: "$4-6" },
    ],
    totalRestaurants: 55, cityRestaurants: 339, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Raise High 🏛️',
  },
  'upenn': {
    slug: 'upenn',
    schoolName: 'University of Pennsylvania',
    shortName: 'UPenn',
    emoji: '🔴',
    mascot: 'Quakers',
    city: 'Philadelphia',
    tagline: 'Penn students save smart',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Shake Shack", category: "Burgers", savings: "$3-5" },
      { name: "Hai Street Kitchen", category: "Asian", savings: "$3-5" },
      { name: "Honeygrow", category: "Bowls", savings: "$3-5" },
    ],
    totalRestaurants: 55, cityRestaurants: 305, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Quakers 🔴',
  },
  'temple': {
    slug: 'temple',
    schoolName: 'Temple University',
    shortName: 'Temple',
    emoji: '🦉',
    mascot: 'Owls',
    city: 'Philadelphia',
    tagline: 'Owls order smarter',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
      { name: "Honeygrow", category: "Bowls", savings: "$3-5" },
      { name: "Halal Guys", category: "Halal", savings: "$3-5" },
    ],
    totalRestaurants: 50, cityRestaurants: 305, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Owls 🦉',
  },
  'tulane': {
    slug: 'tulane',
    schoolName: 'Tulane University',
    shortName: 'Tulane',
    emoji: '🌊',
    mascot: 'Green Wave',
    city: 'New Orleans',
    tagline: 'Roll Wave, save money',
    restaurants: [
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Dat Dog", category: "Hot Dogs", savings: "$3-5" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Willie's Chicken Shack", category: "Chicken", savings: "$3-5" },
      { name: "Reginelli's", category: "Pizza", savings: "$4-6" },
    ],
    totalRestaurants: 50, cityRestaurants: 290, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Roll Wave 🌊',
  },
  'vanderbilt': {
    slug: 'vanderbilt',
    schoolName: 'Vanderbilt University',
    shortName: 'Vandy',
    emoji: '⚓',
    mascot: 'Commodores',
    city: 'Nashville',
    tagline: 'Anchor down on delivery fees',
    restaurants: [
      { name: "Hattie B's", category: "Hot Chicken", savings: "$4-7" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Prince's Hot Chicken", category: "Hot Chicken", savings: "$3-5" },
      { name: "Martin's Bar-B-Que", category: "BBQ", savings: "$4-6" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
    ],
    totalRestaurants: 45, cityRestaurants: 232, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Anchor Down ⚓',
  },
  'uw': {
    slug: 'uw',
    schoolName: 'University of Washington',
    shortName: 'UW',
    emoji: '🐺',
    mascot: 'Huskies',
    city: 'Seattle',
    tagline: 'Huskies save on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Pagliacci Pizza", category: "Pizza", savings: "$3-6" },
      { name: "Thai Tom", category: "Thai", savings: "$3-5" },
      { name: "U:Don", category: "Japanese", savings: "$3-5" },
    ],
    totalRestaurants: 55, cityRestaurants: 315, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Dawgs 🐺',
  },
  // === TIER 3: Fill out remaining metros ===
  'usc': {
    slug: 'usc',
    schoolName: 'USC',
    shortName: 'USC',
    emoji: '✌️',
    mascot: 'Trojans',
    city: 'Los Angeles',
    tagline: 'Fight on, save more',
    restaurants: [
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Dulce", category: "Coffee", savings: "$2-4" },
      { name: "Zankou Chicken", category: "Mediterranean", savings: "$3-5" },
    ],
    totalRestaurants: 65, cityRestaurants: 446, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Fight On ✌️',
  },
  'um': {
    slug: 'um',
    schoolName: 'University of Miami',
    shortName: 'UM',
    emoji: '🙌',
    mascot: 'Hurricanes',
    city: 'Miami',
    tagline: 'Canes save on delivery',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Pollo Tropical", category: "Caribbean", savings: "$3-5" },
      { name: "Flanigan's", category: "American", savings: "$4-6" },
      { name: "Shake Shack", category: "Burgers", savings: "$3-5" },
      { name: "Versailles", category: "Cuban", savings: "$4-6" },
    ],
    totalRestaurants: 60, cityRestaurants: 359, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Canes 🙌',
  },
  'smu': {
    slug: 'smu',
    schoolName: 'SMU',
    shortName: 'SMU',
    emoji: '🐴',
    mascot: 'Mustangs',
    city: 'Dallas',
    tagline: 'Pony up and save',
    restaurants: [
      { name: "Torchy's Tacos", category: "Tacos", savings: "$3-6" },
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Velvet Taco", category: "Tacos", savings: "$4-6" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
    ],
    totalRestaurants: 55, cityRestaurants: 315, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Pony Up 🐴',
  },
  'ucsd': {
    slug: 'ucsd',
    schoolName: 'UC San Diego',
    shortName: 'UCSD',
    emoji: '🔱',
    mascot: 'Tritons',
    city: 'San Diego',
    tagline: 'Tritons save on delivery',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "In-N-Out Burger", category: "Burgers", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "The Taco Stand", category: "Tacos", savings: "$3-5" },
      { name: "Board & Brew", category: "Sandwiches", savings: "$3-5" },
      { name: "Rubio's", category: "Fish Tacos", savings: "$3-5" },
    ],
    totalRestaurants: 50, cityRestaurants: 300, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Tritons 🔱',
  },
  'umn': {
    slug: 'umn',
    schoolName: 'University of Minnesota',
    shortName: 'UMN',
    emoji: '🐿️',
    mascot: 'Golden Gophers',
    city: 'Minneapolis',
    tagline: 'Gophers save on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Punch Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Afro Deli", category: "African", savings: "$3-5" },
      { name: "Surly Brewing", category: "American", savings: "$4-6" },
    ],
    totalRestaurants: 50, cityRestaurants: 292, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Ski-U-Mah 🐿️',
  },
  'usf': {
    slug: 'usf',
    schoolName: 'University of South Florida',
    shortName: 'USF',
    emoji: '🐂',
    mascot: 'Bulls',
    city: 'Tampa',
    tagline: 'Bulls save big',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "PDQ", category: "Chicken", savings: "$3-5" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
      { name: "Zaxby's", category: "Chicken", savings: "$3-5" },
      { name: "Whataburger", category: "Burgers", savings: "$3-5" },
    ],
    totalRestaurants: 45, cityRestaurants: 288, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Bulls 🐂',
  },
  'cu': {
    slug: 'cu',
    schoolName: 'CU Boulder',
    shortName: 'CU',
    emoji: '🦬',
    mascot: 'Buffaloes',
    city: 'Denver',
    tagline: 'Buffs save on delivery',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Illegal Pete's", category: "Burritos", savings: "$3-5" },
      { name: "Cosmo's Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "The Sink", category: "American", savings: "$4-6" },
    ],
    totalRestaurants: 50, cityRestaurants: 283, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Buffs 🦬',
  },
  'pitt': {
    slug: 'pitt',
    schoolName: 'University of Pittsburgh',
    shortName: 'Pitt',
    emoji: '🐆',
    mascot: 'Panthers',
    city: 'Pittsburgh',
    tagline: 'Hail to Pitt, save on eats',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Primanti Brothers", category: "Sandwiches", savings: "$4-6" },
      { name: "Fuel & Fuddle", category: "American", savings: "$3-5" },
      { name: "Sorrento's Pizza", category: "Pizza", savings: "$3-5" },
    ],
    totalRestaurants: 50, cityRestaurants: 307, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Hail to Pitt 🐆',
  },
  'ncstate': {
    slug: 'ncstate',
    schoolName: 'NC State',
    shortName: 'NC State',
    emoji: '🐺',
    mascot: 'Wolfpack',
    city: 'Raleigh',
    tagline: 'Wolfpack saves on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Cookout", category: "Burgers", savings: "$2-4" },
      { name: "Zaxby's", category: "Chicken", savings: "$3-5" },
      { name: "Bojangles", category: "Chicken", savings: "$3-5" },
    ],
    totalRestaurants: 45, cityRestaurants: 263, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Pack 🐺',
  },
  'marquette': {
    slug: 'marquette',
    schoolName: 'Marquette University',
    shortName: 'Marquette',
    emoji: '💛',
    mascot: 'Golden Eagles',
    city: 'Milwaukee',
    tagline: 'We are Marquette, we save money',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Sobelman's", category: "Burgers", savings: "$4-6" },
      { name: "Ian's Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Kopp's Frozen Custard", category: "Dessert", savings: "$2-4" },
    ],
    totalRestaurants: 40, cityRestaurants: 261, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'We Are Marquette 💛',
  },
  'uncc': {
    slug: 'uncc',
    schoolName: 'UNC Charlotte',
    shortName: 'UNCC',
    emoji: '⛏️',
    mascot: '49ers',
    city: 'Charlotte',
    tagline: '49ers dig up savings',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Zaxby's", category: "Chicken", savings: "$3-5" },
      { name: "Bojangles", category: "Chicken", savings: "$3-5" },
      { name: "Cookout", category: "Burgers", savings: "$2-4" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
    ],
    totalRestaurants: 40, cityRestaurants: 260, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Niners ⛏️',
  },
  'wayne': {
    slug: 'wayne',
    schoolName: 'Wayne State University',
    shortName: 'Wayne State',
    emoji: '🏹',
    mascot: 'Warriors',
    city: 'Detroit',
    tagline: 'Warriors save on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Buddy's Pizza", category: "Detroit Style", savings: "$4-6" },
      { name: "Coney Island", category: "American", savings: "$3-5" },
      { name: "Popeyes", category: "Chicken", savings: "$3-5" },
      { name: "Little Caesars", category: "Pizza", savings: "$2-4" },
    ],
    totalRestaurants: 40, cityRestaurants: 262, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Warriors 🏹',
  },
  'jhu': {
    slug: 'jhu',
    schoolName: 'Johns Hopkins University',
    shortName: 'Hopkins',
    emoji: '💙',
    mascot: 'Blue Jays',
    city: 'Baltimore',
    tagline: 'Blue Jays save smart',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Ekiben", category: "Asian Fusion", savings: "$3-5" },
      { name: "Charles Village Pub", category: "American", savings: "$3-5" },
      { name: "Nando's Peri-Peri", category: "Chicken", savings: "$3-5" },
    ],
    totalRestaurants: 45, cityRestaurants: 263, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Blue Jays 💙',
  },
  'butler': {
    slug: 'butler',
    schoolName: 'Butler University',
    shortName: 'Butler',
    emoji: '🐶',
    mascot: 'Bulldogs',
    city: 'Indianapolis',
    tagline: 'Bulldogs save on delivery',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Yats", category: "Cajun", savings: "$3-5" },
      { name: "Bazbeaux Pizza", category: "Pizza", savings: "$3-5" },
      { name: "Steak 'n Shake", category: "Burgers", savings: "$2-4" },
    ],
    totalRestaurants: 40, cityRestaurants: 269, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Dawgs 🐶',
  },
  'berkeley': {
    slug: 'berkeley',
    schoolName: 'UC Berkeley',
    shortName: 'Cal',
    emoji: '🐻',
    mascot: 'Golden Bears',
    city: 'San Francisco',
    tagline: 'Go Bears, save more',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Sweetgreen", category: "Salads", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Sliver Pizzeria", category: "Pizza", savings: "$3-5" },
      { name: "Vik's Chaat", category: "Indian", savings: "$3-5" },
      { name: "Top Dog", category: "Hot Dogs", savings: "$2-3" },
      { name: "Imm Thai Street Food", category: "Thai", savings: "$3-5" },
    ],
    totalRestaurants: 55, cityRestaurants: 306, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Bears 🐻',
  },
  'washu': {
    slug: 'washu',
    schoolName: 'Washington University in St. Louis',
    shortName: 'WashU',
    emoji: '🐻',
    mascot: 'Bears',
    city: 'St. Louis',
    tagline: 'Bears save on delivery',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Insomnia Cookies", category: "Late Night", savings: "$2-4" },
      { name: "Mission Taco Joint", category: "Tacos", savings: "$3-5" },
      { name: "Pi Pizzeria", category: "Deep Dish", savings: "$4-6" },
      { name: "Salt + Smoke", category: "BBQ", savings: "$4-6" },
    ],
    totalRestaurants: 45, cityRestaurants: 302, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Bears 🐻',
  },
  'psu': {
    slug: 'psu',
    schoolName: 'Portland State University',
    shortName: 'PSU',
    emoji: '🌲',
    mascot: 'Vikings',
    city: 'Portland',
    tagline: 'Vikings save on every order',
    restaurants: [
      { name: "Chipotle", category: "Mexican", savings: "$2-4" },
      { name: "Wingstop", category: "Wings", savings: "$3-6" },
      { name: "Five Guys", category: "Burgers", savings: "$3-5" },
      { name: "Raising Cane's", category: "Chicken", savings: "$3-5" },
      { name: "Panda Express", category: "Chinese", savings: "$2-4" },
      { name: "Chick-fil-A", category: "Chicken", savings: "$2-4" },
      { name: "Pine State Biscuits", category: "Breakfast", savings: "$3-5" },
      { name: "Salt & Straw", category: "Dessert", savings: "$2-4" },
      { name: "Voodoo Doughnut", category: "Dessert", savings: "$2-3" },
      { name: "Pok Pok", category: "Thai", savings: "$4-6" },
    ],
    totalRestaurants: 45, cityRestaurants: 278, ordersPerWeek: 3, avgSavings: 5, weeksPerSemester: 16,
    feedbackEmail: 'jon@eddy.delivery', footerSlogan: 'Go Vikings 🌲',
  },
};
